### ISSUE TITLE
Application Icon Missing from Windows 10 "Remove Programs" and "Settings->Apps & Features" menus

### ISSUE THREAD

**Issue by dcyoung** [electron-userland/electron-builder#1108]
* **11.2.4**: 

* **Windows -> NSIS**: 

When installed from NSIS installer, the application is missing an icon in the windows "Remove Programs" menu, as well as the "Settings->Apps & Features" menu. 
![remove_programs](https://cloud.githubusercontent.com/assets/7978433/21906707/31d05e4a-d8c1-11e6-9d97-029d50a09444.PNG)
![apps_features](https://cloud.githubusercontent.com/assets/7978433/21906709/34b42fb0-d8c1-11e6-9986-a56a321f5c0f.PNG)

The application icon IS visible everywhere else (NSIS installer, desktop shortcut, start menu, application executable etc). It may be worth noting that when installed from the Squirrel installer, the application icon is NOT missing from the 2 previously mentioned locations.

Relevant portions of my package.json:

```json
 "build": {
    "appId": "xxx",
     "nsis":{
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true
    },
    "squirrelWindows":{
      "iconUrl": "https://s3.amazonaws.com/xxxx",
      "msi": false
    },
    "win":{
      "target": [
        "nsis",
        "squirrel"
      ],
      "icon": "build/icon.ico"
    }
  }
```

**Comment by roncli** [comment]
Same issue here, I tried an `installerIcon` but that didn't help:

```
    "build": {
        "appId": "com.electron.chattergrid",
        "copyright": "©2016-2017 roncli Productions",
        "productName": "ChatterGrid",
        "compression": "maximum",
        "nsis": {
            "oneClick": false,
            "perMachine": true,
            "allowToChangeInstallationDirectory": true,
            "runAfterFinish": false,
            "installerIcon": "logo/logo.ico"
        },
        "win": {
            "icon": "logo/logo.ico"
        }
    },
```

**Comment by Zamiell** [comment]
Same issue here, app icon is missing using Windows NSIS.
I am on Windows 7 Professional, so this issue seems to affect both Windows 7 and Windows 10.

By the way, in Windows 7, it this feature is called:
"Control Panel" --> "Programs and Features"

Or, from the start menu, it is known as "Add or remove programs".
Or, from the title of the window itself, it says "Uninstall or change a program".
Just adding those here for search-ability reasons.

**Comment by dzunglht** [comment]
Please use iconUrl instead, for example:
"build": {
		"appId": "xxx",
		"win": {
			"target": "nsis",
			"iconUrl": "https://cdn2.iconfinder.com/data/icons/circle-icons-1/64/computer-128.png"
		}
}
Regards

**Comment by develar** [comment]
I will investigate issue this weekend. Sorry for delay.

**Comment by Zamiell** [comment]
No problem, we appreciate all of your hard work. <3

**Comment by develar** [comment]
Fixed by @mbrainiac (thanks!) Will be released as 12.4.0.

**Comment by alanionita** [comment]
This is still happening for me. 

I'm on the following versions: 
```JSON
 "electron": "^2.0.5",
    "electron-builder": "20.24.2",
    "electron-builder-squirrel-windows": "20.24.2",
```

This is my config: 

```JSON
"build": {
    "nodeGypRebuild": false,
    "squirrelWindows": {
      "iconUrl": "http://app.ico"
    },
    "win": {
      "target": "squirrel"
    }
  }
```
