### ISSUE TITLE
electron-gyp install-app-deps

### ISSUE THREAD

**Issue by mtompkins** [electron-userland/electron-builder#1626]
* **Version**: tried: 18.0.1 & 18.5.1

n/a

* **Target**: n/a ... used on linux

Using the following [boilerplate](https://github.com/chentsulin/electron-react-boilerplate) which reproduces the issue for me: 

Today I started to encounter failures with `npm i`. The initial error was to the tune of
```
"EISDIR: illegal operation on a directory, read" on `~./electron-gyp`.  
```
Researching this indicates this is an attempt to read a directory as a file. I thought it might be an `npm` issue as I upgraded it recently and so I reinstalled `node/npm` and removed all remnants including all electron folders, `npm` & `nodejs`. I hadn't narrowed the problem down to the native module build step within `electron-builder` as the boilerplate calls some parallel tasks. I thought a clean reinstall might be the best approach . . .

Reinstalled and configured all those, including moving global `npm node_modules` under the user account to remove any permission issues.

So far so good, however, the previous error now changes to

```
"ENOENT: no such file or directory, open '/home/joe/.electron-gyp'"  
```

which is understandable as I removed this folder. I am unsure as to what this folder gets created and populated.

Continued searching seems to be that the issue is associated with a call to `install-app-deps` and thereby `electron-builder`, but I can't seem to get that to work. 

Creating the directory in advance to see the outcome results in:

```
[3] Error: /usr/bin/node exited with code 235
[3] Error output:
[3] npm ERR! addLocal Could not install /home/joe/.electron-gyp
[3] npm ERR! code EISDIR
[3] npm ERR! errno -21
[3] npm ERR! syscall read
[3] npm ERR! eisdir EISDIR: illegal operation on a directory, read
[3] npm ERR! eisdir This is most likely not a problem with npm itself
[3] npm ERR! eisdir and is related to npm not being able to find a package.json in
[3] npm ERR! eisdir a package you are trying to install.
```
... which is sort of back to the start

Any help is greatly appreciated.

**Comment by neurosnap** [comment]
I'm seeing this issue as well.

**Comment by mtompkins** [comment]
It seems `yarn` doesn't have this issue in my testing FWIW

**Comment by develar** [comment]
Is Yarn affected?

**Comment by mtompkins** [comment]
Yes, although Yarn frustratingly doesn't give an error, `install-app-deps` is failing. After Yarn finished invoking `install-app-deps` will produce the error.

**Comment by develar** [comment]
Yarn works for me. NPM fails because NPM arg parser sucks. I will fix it now.

**Comment by mtompkins** [comment]
No argument here on that claim!... Thanks @develar

**Comment by develar** [comment]
Fixed but please consider to not use NPM. Please use yarn.

**Comment by mtompkins** [comment]
Unfortunately, the change didn't resolve my particular issue. I'm still investigating if it is downstream, however, the output now: 

 ``` [2] Error: /usr/bin/node exited with code 1
[2] Error output:
[2] npm ERR! code ENOLOCAL
[2] npm ERR! Could not install from "../../../.electron-gyp" as it does not contain a package.json file.

```

**Comment by develar** [comment]
Please attach full error stacktrace.

**Comment by develar** [comment]
Please set env DEBUG=electron-builder and attach log of the terminal output.

**Comment by mtompkins** [comment]
Thanks for taking another look, will revert momentarily.

**Comment by SimplyAhmazing** [comment]
I'm getting this error with `18.6.0` node `6.9.4` here's my full stacktrace,


```bash
$ npm i                                        ‹6.9.4› ‹opentrons-api› ‹system› [13:53:37]

> undefined postinstall /Users/me/app
> install-app-deps

Installing app dependencies for arch x64 to /Users/me/app/app
Error: /Users/me/.nodenv/versions/6.9.4/bin/node exited with code 235
Error output:
npm ERR! addLocal Could not install /Users/me/.electron-gyp
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/me/.nodenv/versions/6.9.4/bin/node" "/Users/me/.nodenv/versions/6.9.4/lib/node_modules/npm/bin/npm-cli.js" "install" "--production" "--devdir" "/Users/me/.electron-gyp" "--cache-min" "999999999"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/app/app/npm-debug.log

    at ChildProcess.childProcess.once.code (/Users/me/app/node_modules/electron-builder-util/src/util.ts:135:14)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
From previous event:
    at spawn (/Users/me/app/node_modules/electron-builder-util/src/util.ts:103:3)
    at installDependencies (/Users/me/app/node_modules/electron-builder/src/yarn.ts:77:3)
    at /Users/me/app/node_modules/electron-builder/src/yarn.ts:13:11
    at next (native)
From previous event:
    at installOrRebuild (/Users/me/app/node_modules/electron-builder/out/yarn.js:33:21)
    at /Users/me/app/node_modules/electron-builder/src/cli/install-app-deps.ts:32:2
    at next (native)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
From previous event:
    at main (/Users/me/app/node_modules/electron-builder/out/cli/install-app-deps.js:36:21)
    at Object.<anonymous> (/Users/me/app/node_modules/electron-builder/out/cli/install-app-deps.js:72:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by develar** [comment]
18.6.0 + npm 5 + node 8 works for me. I continue investigation tomorrow, for now please use reliable and not buggy yarn.

**Comment by mtompkins** [comment]
When enabling DEBUG, it hangs at the end so took a few attempts.

Slightly reduced output, full version: https://paste.ee/p/O7Bqx

```
mtompkins@nuc2[±|master U:1 ?:1 ✗]:~/Git/r2 $ DEBUG=electron-builder
mtompkins@nuc2[±|master U:1 ?:1 ✗]:~/Git/r2 $ npm i
npm WARN prefer global colorguard@1.2.0 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> electron-chromedriver@1.7.1 install /home/mtompkins/Git/r2/node_modules/electron-chromedriver
> node ./download-chromedriver.js


> node-sass@4.5.3 install /home/mtompkins/Git/r2/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/mtompkins/.npm/node-sass/4.5.3/linux-x64-57_binding.node

> electron@1.6.10 postinstall /home/mtompkins/Git/r2/node_modules/electron
> node install.js


> node-sass@4.5.3 postinstall /home/mtompkins/Git/r2/node_modules/node-sass
> node scripts/build.js

Binary found at /home/mtompkins/Git/r2/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine

> electron-react-boilerplate@0.12.0 postinstall /home/mtompkins/Git/r2
> concurrently "npm run flow-typed" "npm run build" "npm run build-dll" "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"

[0] 
[0] > electron-react-boilerplate@0.12.0 flow-typed /home/mtompkins/Git/r2
[0] > rimraf flow-typed/npm && flow-typed install --overwrite || true
[0] 
[1] 
[1] > electron-react-boilerplate@0.12.0 build /home/mtompkins/Git/r2
[1] > concurrently "npm run build-main" "npm run build-renderer"
[1] 
[3] Installing app dependencies for arch x64 to /home/mtompkins/Git/r2/app
[4] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 0
[2] 
[2] > electron-react-boilerplate@0.12.0 build-dll /home/mtompkins/Git/r2
[2] > cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --progress --profile --colors
[2] 
[1] [0] 
[1] [0] > electron-react-boilerplate@0.12.0 build-main /home/mtompkins/Git/r2
[1] [0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors
[1] [0] 
[1] [1] 
[1] [1] > electron-react-boilerplate@0.12.0 build-renderer /home/mtompkins/Git/r2
[1] [1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors
[1] [1] 
[3] Error: /usr/bin/node exited with code 235
[3] Error output:
[3] npm ERR! addLocal Could not install /home/mtompkins/.electron-gyp
[3] npm ERR! code EISDIR
[3] npm ERR! errno -21
[3] npm ERR! syscall read
[3] npm ERR! eisdir EISDIR: illegal operation on a directory, read
[3] npm ERR! eisdir This is most likely not a problem with npm itself
[3] npm ERR! eisdir and is related to npm not being able to find a package.json in
[3] npm ERR! eisdir a package you are trying to install.
[3] 

npm ERR! A complete log of this run can be found in:
[3] npm ERR!     /home/mtompkins/.npm/_logs/2017-06-06T18_03_07_359Z-debug.log
[3] 
[3]     at ChildProcess.childProcess.once.code (/home/mtompkins/Git/r2/node_modules/electron-builder-util/src/util.ts:135:14)
[3]     at Object.onceWrapper (events.js:312:19)
[3]     at emitTwo (events.js:125:13)
[3]     at ChildProcess.emit (events.js:213:7)
[3]     at maybeClose (internal/child_process.js:887:16)
[3]     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
[3] From previous event:
[3]     at spawn (/home/mtompkins/Git/r2/node_modules/electron-builder-util/src/util.ts:103:3)
[3]     at installDependencies (/home/mtompkins/Git/r2/node_modules/electron-builder/src/yarn.ts:77:3)
[3]     at /home/mtompkins/Git/r2/node_modules/electron-builder/src/yarn.ts:13:11
[3]     at Generator.next (<anonymous>)
[3] From previous event:
[3]     at installOrRebuild (/home/mtompkins/Git/r2/node_modules/electron-builder/out/yarn.js:33:21)
[3]     at /home/mtompkins/Git/r2/node_modules/electron-builder/src/cli/install-app-deps.ts:32:2
[3]     at Generator.next (<anonymous>)
[3]     at runCallback (timers.js:800:20)
[3]     at tryOnImmediate (timers.js:762:5)
[3] From previous event:
[3]     at main (/home/mtompkins/Git/r2/node_modules/electron-builder/out/cli/install-app-deps.js:36:21)
[3]     at Object.<anonymous> (/home/mtompkins/Git/r2/node_modules/electron-builder/out/cli/install-app-deps.js:72:1)
[3]     at Module._compile (module.js:569:30)
[3]     at Object.Module._extensions..js (module.js:580:10)
[3]     at Module.load (module.js:503:32)
[3]     at tryModuleLoad (module.js:466:12)
[3]     at Function.Module._load (module.js:458:3)
[3]     at Function.Module.runMain (module.js:605:10)
[3]     at startup (bootstrap_node.js:158:16)
[3]     at bootstrap_node.js:575:3
[3] install-app-deps exited with code 255
] • Found 84 dependencies in package.json to install libdefs for. Searching...
[0] • rebasing flow-typed cache...
[2]   0% compiling
....
....
....
[1] [1]	 92% chunk asset optimization
440ms1chunk asset optimization
[1] [1]	 94% asset optimization
[1] [1]
[1] [1] 0ms asset optimization
[1] [1]	 95% emitting
72ms[emitting
[1] [1] Hash: fb4208c08bd427360f02
[1] [1] Version: webpack 2.6.1
[1] [1] Time: 32662ms
[1] [1]					 Asset	    Size  Chunks		    Chunk Names
[1] [1]	  674f50d287a8c48dc19ba404d20fe713.eot	  166 kB	  [emitted]
[1] [1]	  912ec66d7572ff821749319396470bde.svg	  444 kB	  [emitted]  [big]
[1] [1]	  b06871f281fee6b241d60582ae9369b9.ttf	  166 kB	  [emitted]
[1] [1] af7ae505a9eed503f8b8e6982036873e.woff2	 77.2 kB	  [emitted]
[1] [1]	 fee66e712a8a08eef5805a46892932ad.woff	   98 kB	  [emitted]
[1] [1]				     bundle.js	  448 kB       0  [emitted]  [big]  main
[1] [1]				     style.css	 38.9 kB       0  [emitted]	    main
[1] [1]				 bundle.js.map	 1.35 MB       0  [emitted]	    main
[1] [1]				 style.css.map	86 bytes       0  [emitted]	    main
[1] [1] [./app/app.global.css] ./app/app.global.css 41 bytes {0} [built]
[1] [1]	       [] -> factory:1985ms building:147ms = 2132ms
[1] [1] [./app/containers/Root.js] ./app/containers/Root.js 1.66 kB {0} [built]
[1] [1]	       [] -> factory:246ms building:3983ms dependencies:41ms = 4270ms
[1] [1] [./app/index.js] ./app/index.js 1.97 kB {0} [built]
[1] [1]	       [] -> factory:74ms building:651ms = 725ms
[1] [1] [./app/store/configureStore.js] ./app/store/configureStore.js 251 bytes {0} [built]
[1] [1]	       [] -> factory:247ms building:3988ms = 4235ms
[1] [1] [./node_modules/babel-polyfill/lib/index.js] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
[1] [1]	       [] -> factory:65ms building:73ms = 138ms
[1] [1] [./node_modules/babel-polyfill/node_modules/core-js/fn/regexp/escape.js] ./~/babel-polyfill/~/core-js/fn/regexp/escape.js 107 bytes {0} [built]
[1] [1]	       [] -> factory:434ms building:379ms dependencies:559ms = 1372ms
[1] [1] [./node_modules/babel-polyfill/node_modules/core-js/modules/es6.number.constructor.js] ./~/babel-polyfill/~/core-js/modules/es6.number.constructor.js 2.93 kB {0} [built]
[1] [1]	       [] -> factory:414ms building:510ms dependencies:2296ms = 3220ms
[1] [1] [./node_modules/babel-polyfill/node_modules/core-js/shim.js] ./~/babel-polyfill/~/core-js/shim.js 7.38 kB {0} [built]
[1] [1]	       [] -> factory:434ms building:247ms = 681ms
[1] [1] [./node_modules/react-dom/index.js] ./~/react-dom/index.js 59 bytes {0} [built]
[1] [1]	       [] -> factory:816ms building:2628ms = 3444ms
[1] [1] [./node_modules/react-hot-loader/index.js] ./~/react-hot-loader/index.js 41 bytes {0} [built]
[1] [1]	       [] -> factory:819ms building:2626ms = 3445ms
[1] [1] [./node_modules/react-router-redux/es/index.js] ./~/react-router-redux/es/index.js 356 bytes {0} [built]
[1] [1]	       [] -> factory:146ms building:1014ms = 1160ms
[1] [1]	   [0] multi babel-polyfill ./app/index 40 bytes {0} [built]
[1] [1]		factory:1ms building:5ms = 6ms
[1] [1] [./node_modules/react/react.js] ./~/react/react.js 56 bytes {0} [built]
[1] [1]	       [] -> factory:815ms building:2628ms = 3443ms
[1] [1] [./node_modules/regenerator-runtime/runtime.js] ./~/regenerator-runtime/runtime.js 24.4 kB {0} [built]
[1] [1]	       [] -> factory:424ms building:122ms = 546ms
[1] [1] [./node_modules/style-loader/lib/addStyles.js] ./~/style-loader/lib/addStyles.js 8.7 kB [built]
[1] [1]	       [] -> factory:1318ms building:839ms = 2157ms
[1] [1]	    + 563 hidden modules
[1] [1] Child extract-text-webpack-plugin:
[1] [1]	    [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
[1] [1]		   [] -> factory:18ms building:3ms = 21ms
[1] [1]		+ 1 hidden modules
[1] [1] Child extract-text-webpack-plugin:
[1] [1]	    [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
[1] [1]		   [] -> factory:17ms building:6ms = 23ms
[1] [1]		+ 1 hidden modules
[1] [1] Child extract-text-webpack-plugin:
[1] [1]	    [./node_modules/css-loader/index.js!./app/app.global.css] ./~/css-loader!./app/app.global.css 860 bytes {0} [built]
[1] [1]		    factory:15ms building:105ms = 120ms
[1] [1]	    [./node_modules/css-loader/index.js!./node_modules/font-awesome/css/font-awesome.css] ./~/css-loader!./~/font-awesome/css/font-awesome.css 42 kB {0} [built]
[1] [1]		   [] -> factory:30ms building:341ms dependencies:19ms = 390ms
[1] [1]	    [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
[1] [1]		   [] -> factory:10ms building:14ms = 24ms
[1] [1]	    [./node_modules/font-awesome/fonts/fontawesome-webfont.eot] ./~/font-awesome/fonts/fontawesome-webfont.eot 82 bytes {0} [built]
[1] [1]		   [] -> factory:31ms building:5ms = 36ms
[1] [1]	    [./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0] ./~/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0 82 bytes {0} [built]
[1] [1]		   [] -> factory:30ms building:5ms = 35ms
[1] [1]	    [./node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0] ./~/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0 82 bytes {0} [built]
[1] [1]		   [] -> factory:30ms building:4ms = 34ms
[1] [1]	    [./node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0] ./~/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 82 bytes {0} [built]
[1] [1]		   [] -> factory:30ms building:3ms = 33ms
[1] [1]	    [./node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0] ./~/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 84 bytes {0} [built]
[1] [1]		   [] -> factory:26ms building:5ms = 31ms
[1] [1]	    [./node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0] ./~/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0 83 bytes {0} [built]
[1] [1]		   [] -> factory:30ms building:2ms = 32ms
[1] [1] npm run build-renderer exited with code 0
[1] npm run build exited with code 0
^[[6~^[[6~^[[6~^[[6~^[[6~^[[6~^[[6~^C[0] npm run flow-typed exited with code 0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.1.0 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.12.0 postinstall: `concurrently "npm run flow-typed" "npm run build" "npm run build-dll" "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mtompkins/.npm/_logs/2017-06-06T18_07_17_420Z-debug.log
```

**Comment by develar** [comment]
Please try 18.6.1 (please note — it is next version).

**Comment by mtompkins** [comment]
I'm finding 18.6.1 is hanging / not completing presumably on the `install-app-deps` call.

**Comment by develar** [comment]
Please try withou DEBUG.

**Comment by mtompkins** [comment]
I'm able to reproduce the hang behavior with the template by:
```
git clone --depth=1 https://github.com/chentsulin/electron-react-boilerplate.git r2
cd r2
npm remove --save-dev electron-builder && npm i --save-dev electron-builder@18.6.1
npm i
```

**Comment by mtompkins** [comment]
Minor update - between Github outages and as I've been able, I cannot say that the hang I am experiencing is a result of 18.6.1. I'll try to provide a better status tomorrow.

**Comment by develar** [comment]
Should be fixed now. If not — get rid of NPM and please use reliable yarn.

**Comment by mtompkins** [comment]
I can confirm that your update did resolve the issue - thanks so much.
My versions: 

- electron-builder: 18.6.1
- node 8.0.0.
- yarn 0.24.6

Much appreciated @develar

**Comment by black-snow** [comment]
@develar switched to yarn, deleted my `node_modules`

`yarn`:

```
Der Befehl "install-app-deps" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
error Command failed with exit code 1.
```

:{
yarn 0.24.6
node v8.1.0
electron-builder 18.6.2

**Comment by develar** [comment]
@black-snow Please provide your package.json What do you see in the `node_modules/.bin`?

**Comment by black-snow** [comment]
There, in fact, is no install-app-deps; bin contents:

```
semver
semver.cmd
```

Funnily, there ain't no electron-builder inside `node-modules` - gonna investigate

**Comment by black-snow** [comment]
Works fine with npm :P

**Comment by black-snow** [comment]
Created an issue [here](https://github.com/yarnpkg/yarn/issues/3616)

**Comment by VikasAlgoworks** [comment]
Hi guys, 
I am stuck here could you please help me here
 10% building modules 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8000/
ℹ ｢wds｣: webpack output is served from /
 10% building modules 1/2 modules 1 active …r/client/index.js?http://localhost:8000ℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: Hash: 38fed4fa0554bc0b8caa
Version: webpack 4.12.0
Time: 23933ms
Built at: 06/28/2018 6:26:12 PM
 2 assets
Entrypoint main = bundle.js main.styles.css
[./app/main.js] ./app/main.js + 130 modules 374 KiB {0} [built]
    | ./app/components/Header/header.js 9.43 KiB [built]
    | ./app/main.js 236 bytes [built]
    | ./node_modules/history/es/index.js 460 bytes [built]
    | ./app/components/Login/login.js 3.96 KiB [built]
    | ./app/components/Dashboard/dashboard.js 315 bytes [built]
    | ./node_modules/history/es/createHashHistory.js 9.16 KiB [built]
    | ./node_modules/history/es/createMemoryHistory.js 5.27 KiB [built]
    | ./app/components/App.js 1.2 KiB [built]
    | ./node_modules/react-router-dom/es/Router.js 131 bytes [built]
    | ./node_modules/react-router-dom/es/Route.js 128 bytes [built]
    | ./node_modules/react-router-dom/es/Switch.js 131 bytes [built]
    | ./app/constant/constant.js 3.61 KiB [built]
    | ./app/Apis/api.js 1.02 KiB [built]
    | ./node_modules/history/es/PathUtils.js 1.57 KiB [built]
    | ./app/components/Footer/footer.js 446 bytes [built]
    |     + 116 hidden modules
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {0} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {0} [built]
[./node_modules/react-fontawesome/lib/index.js] 6.85 KiB {0} [built]
[./node_modules/react/index.js] 190 bytes {0} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {0} [built]
[./node_modules/url/url.js] 22.8 KiB {0} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8000] (webpack)-dev-server/client?http://localhost:8000 7.75 KiB {0} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {0} [built]
[0] multi (webpack)-dev-server/client?http://localhost:8000 webpack/hot/dev-server ./app/main.js 52 bytes {0} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {0} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.6 KiB {0} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {0} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {0} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1010 bytes {0} [built]
    + 282 hidden modules

WARNING in ./app/Apis/api.js 6:14-34
"export 'ADMIN_LOGIN' (imported as 'CONSTANT') was not found in '../constant/constant'
 @ ./app/components/Login/login.js
 @ ./app/components/App.js
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8000 webpack/hot/dev-server ./app/main.js

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./node_modules/font-awesome/css/font-awesome.min.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
    at handleParseError (/Users/vikassharma/Documents/cheehoo-admin/node_modules/webpack/lib/NormalModule.js:449:19)
    at doBuild.err (/Users/vikassharma/Documents/cheehoo-admin/node_modules/webpack/lib/NormalModule.js:483:5)
    at runLoaders (/Users/vikassharma/Documents/cheehoo-admin/node_modules/webpack/lib/NormalModule.js:344:12)
    at /Users/vikassharma/Documents/cheehoo-admin/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/vikassharma/Documents/cheehoo-admin/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at /Users/vikassharma/Documents/cheehoo-admin/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at process.nextTick (/Users/vikassharma/Documents/cheehoo-admin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./node_modules/font-awesome/css/font-awesome.min.css

ERROR in ./node_modules/font-awesome/css/font-awesome.min.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
    at handleParseError (/Users/vikassharma/Documents/cheehoo-admin/node_modules/webpack/lib/NormalModule.js:449:19)
    at doBuild.err (/Users/vikassharma/Documents/cheehoo-admin/node_modules/webpack/lib/NormalModule.js:483:5)
    at runLoaders (/Users/vikassharma/Documents/cheehoo-admin/node_modules/webpack/lib/NormalModule.js:344:12)
    at /Users/vikassharma/Documents/cheehoo-admin/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/vikassharma/Documents/cheehoo-admin/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/Users/vikassharma/Documents/cheehoo-admin/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/vikassharma/Documents/cheehoo-admin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/Users/vikassharma/Documents/cheehoo-admin/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /Users/vikassharma/Documents/cheehoo-admin/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:3)
 @ ./app/components/App.js 14:0-47
 @ ./app/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8000 webpack/hot/dev-server ./app/main.js
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/font-awesome/css/font-awesome.min.css:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js!./node_modules/font-awesome/css/font-awesome.min.css] ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css 32.6 KiB {0} [built]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {0} [built]
    [./node_modules/css-loader/lib/url/escape.js] 448 bytes {0} [built]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.eot] 177 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0] 177 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0] 286 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0] 182 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0] 182 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0] 182 bytes {0} [built] [failed] [1 error]

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 1:0
    Module parse failed: Unexpected character '' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:615-666

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 1:4
    Module parse failed: Unexpected character '' (1:4)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:435-488

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0 1:4
    Module parse failed: Unexpected character '' (1:4)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:526-578

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0 1:1
    Module parse failed: Unexpected character '�' (1:1)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:250-301

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot 1:1
    Module parse failed: Unexpected character '�' (1:1)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:327-370

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    > <?xml version="1.0" standalone="no"?>
    | <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
    | <svg>
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:707-758
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/font-awesome/css/font-awesome.min.css:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js!./node_modules/font-awesome/css/font-awesome.min.css] ./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css 32.6 KiB {0} [built]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {0} [built]
    [./node_modules/css-loader/lib/url/escape.js] 448 bytes {0} [built]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.eot] 177 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0] 177 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0] 286 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0] 182 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0] 182 bytes {0} [built] [failed] [1 error]
    [./node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0] 182 bytes {0} [built] [failed] [1 error]

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 1:0
    Module parse failed: Unexpected character '' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:615-666

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 1:4
    Module parse failed: Unexpected character '' (1:4)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:435-488

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.woff?v=4.7.0 1:4
    Module parse failed: Unexpected character '' (1:4)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:526-578

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot?v=4.7.0 1:1
    Module parse failed: Unexpected character '�' (1:1)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:250-301

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.eot 1:1
    Module parse failed: Unexpected character '�' (1:1)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:327-370

    ERROR in ./node_modules/font-awesome/fonts/fontawesome-webfont.svg?v=4.7.0 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    > <?xml version="1.0" standalone="no"?>
    | <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
    | <svg>
     @ ./node_modules/font-awesome/css/font-awesome.min.css (./node_modules/css-loader!./node_modules/font-awesome/css/font-awesome.min.css) 7:707-758
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--5-3!node_modules/sass-loader/lib/loader.js!app/components/custom.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js??ref--5-3!./node_modules/sass-loader/lib/loader.js!./app/components/custom.scss] ./node_modules/css-loader??ref--5-3!./node_modules/sass-loader/lib/loader.js!./app/components/custom.scss 349 bytes {0} [built]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--5-3!node_modules/sass-loader/lib/loader.js!app/components/slim.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js??ref--5-3!./node_modules/sass-loader/lib/loader.js!./app/components/slim.scss] ./node_modules/css-loader??ref--5-3!./node_modules/sass-loader/lib/loader.js!./app/components/slim.scss 1020 KiB {0} [built]
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {0} [built]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 739 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.
