### ISSUE TITLE
Jenkins CI gives error: unknown error -1=ffffffffffffffff

### ISSUE THREAD

**Issue by noahbenham** [electron-userland/electron-builder#1669]
* **Version**: 18.8.1

* **Target**: Mac Default / Windows NSIS

macOS: `10.12.5 (16F73)`
Xcode: `8.3.3 (8E3004b)`

I'm attempting to codesign from a Jenkins CI and receiving errors.
From VNC non-headless terminal in workspace folder, getting `nested code is modified or invalid`.
From Jenkins headless build, getting `unknown error -1=ffffffffffffffff`.

Keychain `login` has both Developer ID Application and Developer ID Installer certs and private keys.

`package.json` build section:
```
"build": {
    "appId": "__removed__",
    "copyright": "Copyright 2016 __removed__. All rights reserved.",
    "productName": "__removed__",
    "mac": {
      "category": "public.app-category.medical"
    },
    "win": {
      "target": "nsis"
    },
    "nsis": {
      "perMachine": true,
      "runAfterFinish": false
    }
  },
```

npm ls --prod:
```
├── electron-is-dev@0.1.2
├─┬ ibus-logging@1.0.0
│ └── canadarm@1.0.2
├─┬ js-yaml@3.8.4
│ ├─┬ argparse@1.0.9
│ │ └── sprintf-js@1.0.3
│ └── esprima@3.1.3
├── keymirror@0.1.1
├─┬ menubar@5.2.3
│ ├── electron-positioner@3.0.0
│ └── extend@2.0.1
├─┬ request@2.81.0
│ ├── aws-sign2@0.6.0
│ ├── aws4@1.6.0
│ ├── caseless@0.12.0
│ ├─┬ combined-stream@1.0.5
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.1
│ ├── forever-agent@0.6.1
│ ├─┬ form-data@2.1.4
│ │ ├── asynckit@0.4.0
│ │ ├── combined-stream@1.0.5 deduped
│ │ └── mime-types@2.1.15 deduped
│ ├─┬ har-validator@4.2.1
│ │ ├─┬ ajv@4.11.8
│ │ │ ├── co@4.6.0
│ │ │ └─┬ json-stable-stringify@1.0.1
│ │ │   └── jsonify@0.0.0
│ │ └── har-schema@1.0.5
│ ├─┬ hawk@3.1.3
│ │ ├─┬ boom@2.10.1
│ │ │ └── hoek@2.16.3 deduped
│ │ ├─┬ cryptiles@2.0.5
│ │ │ └── boom@2.10.1 deduped
│ │ ├── hoek@2.16.3
│ │ └─┬ sntp@1.0.9
│ │   └── hoek@2.16.3 deduped
│ ├─┬ http-signature@1.1.1
│ │ ├── assert-plus@0.2.0
│ │ ├─┬ jsprim@1.4.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├── extsprintf@1.0.2
│ │ │ ├── json-schema@0.2.3
│ │ │ └─┬ verror@1.3.6
│ │ │   └── extsprintf@1.0.2 deduped
│ │ └─┬ sshpk@1.13.0
│ │   ├── asn1@0.2.3
│ │   ├── assert-plus@1.0.0 deduped
│ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │   │ └── tweetnacl@0.14.5 deduped
│ │   ├─┬ dashdash@1.14.1
│ │   │ └── assert-plus@1.0.0 deduped
│ │   ├─┬ ecc-jsbn@0.1.1
│ │   │ └── jsbn@0.1.1 deduped
│ │   ├─┬ getpass@0.1.7
│ │   │ └── assert-plus@1.0.0 deduped
│ │   ├─┬ jodid25519@1.0.2
│ │   │ └── jsbn@0.1.1 deduped
│ │   ├── jsbn@0.1.1
│ │   └── tweetnacl@0.14.5
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.15
│ │ └── mime-db@1.27.0
│ ├── oauth-sign@0.8.2
│ ├── performance-now@0.2.0
│ ├── qs@6.4.0
│ ├── safe-buffer@5.1.0
│ ├── stringstream@0.0.5
│ ├─┬ tough-cookie@2.3.2
│ │ └── punycode@1.4.1
│ ├─┬ tunnel-agent@0.6.0
│ │ └── safe-buffer@5.1.0 deduped
│ └── uuid@3.0.1
├── ua-parser-js@0.7.12
└── valid-url@1.0.9
```

##### Additional environment vars
`DEBUG=electron-osx-sign`
##### Output
```
./build.sh -m -dev
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ install-app-deps
No native production dependencies
✨  Done in 4.39s.
yarn test v0.24.6
$ istanbul cover node_modules/jasmine/bin/jasmine.js 
Started
............................................................................................................................................................


156 specs, 0 failures
Finished in 6.922 seconds


=============================== Coverage summary ===============================
Statements   : 83.78% ( 1674/1998 )
Branches     : 56.15% ( 201/358 )
Functions    : 87% ( 435/500 )
Lines        : 83.99% ( 1647/1961 )
================================================================================
✨  Done in 16.20s.
yarn run v0.24.6
$ eslint . 
✨  Done in 3.97s.
Building for platform mac
yarn run v0.24.6
$ yarn run less && build -m --em.version=1.2.0-a170613-1359
yarn run v0.24.6
$ lessc --clean-css less/main.less app/styles.min.css 
✨  Done in 0.51s.
electron-builder 18.8.1
No native production dependencies
Packaging for darwin x64 using electron 1.6.10 to dist/mac
Signing app (identity: Developer ID Application: Corporation (U2......2F))
 electron-osx-sign `identity` passed in arguments. +0ms
 electron-osx-sign Pre-sign operation enabled for provisioning profile: 
* Disable by setting `pre-embed-previsioning-profile` to `false`. +2ms
 electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`: 
* Disable by setting `pre-auto-entitlements` to `false`. +1ms
 electron-osx-sign No `provisioning-profile` passed in arguments, will find in current working directory and in user library... +1ms
 electron-osx-sign No provisioning profile found, will not embed profile in app contents. +2ms
 electron-osx-sign Signing application... 
> Application: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app 
> Platform: darwin 
> Entitlements: undefined 
> Child entitlements: undefined 
> Additional binaries: undefined 
> Identity: { name: 'Developer ID Application: Corporation (U2......2F)',
 hash: undefined } +1ms
 electron-osx-sign Walking... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents +3ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app/Contents/MacOS/ProductNameRemoved Helper EH +186ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app/Contents/MacOS/ProductNameRemoved Helper EH +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app +906ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper NP.app/Contents/MacOS/ProductNameRemoved Helper NP +593ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper NP.app/Contents/MacOS/ProductNameRemoved Helper NP +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper NP.app +567ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper NP.app +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper.app/Contents/MacOS/ProductNameRemoved Helper +446ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper.app/Contents/MacOS/ProductNameRemoved Helper +1ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper.app +431ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper.app +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +458ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +1ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +2s
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib +1ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +558ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crashpad_handler +1s
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crashpad_handler +1ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework +624ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework +1ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle +2s
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle +1ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Mantle.framework +507ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Mantle.framework +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa +490ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ReactiveCocoa.framework +550ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ReactiveCocoa.framework +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt +483ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Squirrel.framework/Versions/A/Resources/ShipIt +1ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel +454ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel +1ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Squirrel.framework +576ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Squirrel.framework +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/MacOS/ProductNameRemoved +537ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/MacOS/ProductNameRemoved +0ms
 electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app +540ms
 electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app +0ms
 electron-osx-sign Verifying... +527ms
 electron-osx-sign Verifying application bundle with codesign... +1ms
 electron-osx-sign Executing... codesign --verify --deep --verbose=2 --strict /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app +1ms
 electron-osx-sign Error executing file: 
> Stdout: file modified: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app
file modified: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper NP.app
file modified: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper.app
file modified: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Electron Framework.framework
file modified: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Mantle.framework
file modified: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ReactiveCocoa.framework
file modified: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/Squirrel.framework

> Stderr: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app: nested code is modified or invalid
+978ms
Error: Command failed: codesign --verify --deep --verbose=2 --strict /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app
/Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app: nested code is modified or invalid

   at ChildProcess.exithandler (child_process.js:252:12)
   at emitTwo (events.js:125:13)
   at ChildProcess.emit (events.js:213:7)
   at maybeClose (internal/child_process.js:887:16)
   at Socket.stream.socket.on (internal/child_process.js:340:11)
   at emitOne (events.js:115:13)
   at Socket.emit (events.js:210:7)
   at Pipe._handle.close [as _onclose] (net.js:548:12)
From previous event:
   at MacPackager.sign (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/macPackager.js:292:11)
   at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/macPackager.ts:92:26
   at runCallback (timers.js:800:20)
   at tryOnImmediate (timers.js:762:5)
   at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
   at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/macPackager.ts:92:10
   at Generator.next (<anonymous>)
From previous event:
   at MacPackager.pack (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/macPackager.js:189:11)
   at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/packager.ts:270:24
   at Generator.next (<anonymous>)
   at xfs.stat (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
   at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/graceful-fs/polyfills.js:287:18
   at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
   at Packager.doBuild (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/packager.js:388:11)
   at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/packager.ts:183:52
   at Generator.next (<anonymous>)
   at runCallback (timers.js:800:20)
   at tryOnImmediate (timers.js:762:5)
   at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
   at Packager.build (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/packager.js:283:11)
   at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/builder.ts:199:33
   at Generator.next (<anonymous>)
From previous event:
   at build (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/builder.js:70:21)
   at Object.<anonymous> (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/cli/build-cli.js:71:41)
   at Module._compile (module.js:569:30)
   at Object.Module._extensions..js (module.js:580:10)
   at Module.load (module.js:503:32)
   at tryModuleLoad (module.js:466:12)
   at Function.Module._load (module.js:458:3)
   at Function.Module.runMain (module.js:605:10)
   at startup (bootstrap_node.js:158:16)
   at bootstrap_node.js:575:3
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

##### Additional environment vars
```
DEBUG=electron-osx-sign
CSC_LINK=/Users/jenkins/Desktop/Cert.p12
CSC_KEY_PASSWORD=___pass_removed___
CSC_IDENTITY_AUTO_DISCOVERY=false
```
##### Output
```
Started by user Noah Benham
[EnvInject] - Loading node environment variables.
Building remotely on mac-build-28 (MAC) in workspace /Users/Jenkins/jenkins/workspace/workspace-name-removed
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://___giturl_removed___ # timeout=10
Fetching upstream changes from https://___giturl_removed___
 > git --version # timeout=10
 > git fetch --tags --progress https://___giturl_removed___ +refs/heads/*:refs/remotes/origin/*
 > git rev-parse origin/dev^{commit} # timeout=10
Checking out Revision a7fa4155ae7e819d43b872732c373592e92c12a2 (origin/dev)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a7fa4155ae7e819d43b872732c373592e92c12a2
 > git rev-list a7fa4155ae7e819d43b872732c373592e92c12a2 # timeout=10
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - Injecting as environment variables the properties content 
DEBUG=electron-osx-sign
CSC_KEY_PASSWORD=___pass_removed___
CSC_LINK=/Users/jenkins/Desktop/Cert.p12
CSC_IDENTITY_AUTO_DISCOVERY=false

[EnvInject] - Variables injected successfully.
[workspace-name-removed] $ /bin/bash -xe /var/folders/v5/vmqf79rs09jfd1kq4g5p4pg80000gn/T/hudson3578419999051454549.sh
+ source /etc/profile
++ '[' -x /usr/libexec/path_helper ']'
+++ /usr/libexec/path_helper -s
++ eval 'PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Jenkins/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Latest_Node/bin";' export 'PATH;'
+++ PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Jenkins/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Latest_Node/bin
+++ export PATH
++ '[' /bin/bash '!=' no ']'
++ '[' -r /etc/bashrc ']'
++ . /etc/bashrc
+++ '[' -z '' ']'
+++ return
+ ./build.sh -m -dev
yarn install v0.24.6
[1/4] Resolving packages...
success Already up-to-date.
$ install-app-deps
No native production dependencies
Done in 4.44s.
yarn test v0.24.6
$ istanbul cover node_modules/jasmine/bin/jasmine.js 
Started
............................................................................................................................................................


156 specs, 0 failures
Finished in 6.495 seconds


=============================== Coverage summary ===============================
Statements   : 83.78% ( 1674/1998 )
Branches     : 56.15% ( 201/358 )
Functions    : 87% ( 435/500 )
Lines        : 83.99% ( 1647/1961 )
================================================================================
Done in 16.41s.
yarn run v0.24.6
$ eslint . 
Done in 3.94s.
Building for platform mac
yarn run v0.24.6
$ yarn run less && build -m --em.version=1.2.0-a170613-1430
yarn run v0.24.6
$ lessc --clean-css less/main.less app/styles.min.css 
Done in 0.50s.
electron-builder 18.8.1
CI detected, so artifacts will be published if draft release exists
No native production dependencies
Packaging for darwin x64 using electron 1.6.10 to dist/mac
Signing app (identity: Developer ID Application: Corporation (U2......2F))
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign `identity` passed in arguments.
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign Pre-sign operation enabled for provisioning profile: 
 * Disable by setting `pre-embed-previsioning-profile` to `false`.
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign Pre-sign operation enabled for entitlements automation with versions >= `1.1.1`: 
 * Disable by setting `pre-auto-entitlements` to `false`.
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign No `provisioning-profile` passed in arguments, will find in current working directory and in user library...
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign No provisioning profile found, will not embed profile in app contents.
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign Signing application... 
 > Application: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app 
 > Platform: darwin 
 > Entitlements: undefined 
 > Child entitlements: undefined 
 > Additional binaries: undefined 
 > Identity: { name: 'Developer ID Application: Corporation (U2......2F)',
  hash: undefined }
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign Walking... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign Signing... /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app/Contents/MacOS/ProductNameRemoved Helper EH
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign Executing... codesign --sign Developer ID Application: Corporation (U2......2F) --force --keychain /var/folders/v5/vmqf79rs09jfd1kq4g5p4pg80000gn/T/electron-builder-kFrykX/0-1.keychain /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app/Contents/MacOS/ProductNameRemoved Helper EH
Tue, 13 Jun 2017 19:30:45 GMT electron-osx-sign Error executing file: 
 > Stdout:  
 > Stderr: /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app/Contents/MacOS/ProductNameRemoved Helper EH: unknown error -1=ffffffffffffffff

Error: Command failed: codesign --sign Developer ID Application: Corporation (U2......2F) --force --keychain /var/folders/v5/vmqf79rs09jfd1kq4g5p4pg80000gn/T/electron-builder-kFrykX/0-1.keychain /Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app/Contents/MacOS/ProductNameRemoved Helper EH
/Users/jenkins/jenkins/workspace/workspace-name-removed/dist/mac/ProductNameRemoved.app/Contents/Frameworks/ProductNameRemoved Helper EH.app/Contents/MacOS/ProductNameRemoved Helper EH: unknown error -1=ffffffffffffffff

    at ChildProcess.exithandler (child_process.js:252:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at MacPackager.sign (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/macPackager.js:292:11)
    at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/macPackager.ts:92:26
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/macPackager.ts:92:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/macPackager.js:189:11)
    at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/packager.ts:270:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager.doBuild (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/packager.js:388:11)
    at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/packager.ts:183:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/packager.js:283:11)
    at /Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/src/builder.ts:199:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/jenkins/jenkins/workspace/workspace-name-removed/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure
Archiving artifacts
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE
```

**Comment by develar** [comment]
Fixed in 19.5.1.

**Comment by noahbenham** [comment]
Thanks @develar. I'm no longer getting `unknown error` with 19.5.1. However, I'm still seeing `nested code is modified or invalid`. Have you tested with Xcode 8.3.3? I wonder if I need to downgrade. Possibly similar to #559.

**Comment by noahbenham** [comment]
Found solution. I had set keychain cert codesign settings to `always trust`. Changed to system default and build is now completing. Thank you!
