### ISSUE TITLE
Symbolic linked dependency's node_modules is not included in ASAR

### ISSUE THREAD

**Issue by guiguan** [electron-userland/electron-builder#1837]
* **Version**:  19.16.1

* **Target**: `mac --dir`

If the dependency listed in `package.json` is a symbolic link, for example, created by `yarn link`, then that dependency's `node_modules` is not included in final ASAR, which made target app unable to run. This worked in `electron-builder 19.10.0`

@wshamim

**Comment by dgeibi** [comment]
I have the same problem after running `lerna bootstrap` or `npm link xx`.

**Comment by develar** [comment]
Consider to use yarn workspaces as workaround.

**Comment by dgeibi** [comment]
Yarn workspaces didn't help.

- yarn: v1.0.1
- electron-builder: v19.28.1
- Target: AppImage

**Comment by develar** [comment]
I hope it is fixed now.

**Comment by dsanders11** [comment]
@develar, this is still a problem for me. Dependencies which were symbolically linked via `yarn link` do not get packaged.
