### ISSUE TITLE
Uninstaller permission on 2nd invocation of exe installer

### ISSUE THREAD

**Issue by arkakkar** [electron-userland/electron-builder#2225]
electron-builder : 19.27.7
electron-updater: 2.8.9
Platform : WIndows 10

Target: NSIS

On a clean machine, installation works fine, the first time.
On an already installed app, tried running setup again or auto-updating (since auto update also installs the downloaded executable), the setup proceeds with first uninstalling the previous version and reinstalling the new version.

Allowed (User Account Control) prompt while installing as well as updating but throws an error while uninstalling the previous version. Happens on some machines and not all machines.

Confirmed the erroneous machine user is an admin user.

This the error popup I get while installing/updating the app
![pasted image at 2017_10_17 11_20 am](https://user-images.githubusercontent.com/13099382/31983475-054b3dfe-b97b-11e7-8af6-26fd3881b113.png)

On erroneous machines, tried running the uninstaller through the file system also throws

<img width="603" alt="screen shot 2017-10-25 at 11 57 28 am" src="https://user-images.githubusercontent.com/13099382/31983637-b43e4a4a-b97b-11e7-9405-461887f58502.png">

These are my NSIS build configuration
"nsis": {
"oneClick": false,
"perMachine": true,
"allowElevation": true,
"allowToChangeInstallationDirectory": true,
"menuCategory": true,
"installerIcon": "./icons/win.ico",
"uninstallerIcon": "./icons/win.ico",
"uninstallDisplayName": "${productName} ${version}",
"installerSidebar": "./build/installerSidebar.bmp",
"deleteAppDataOnUninstall": true
}

**My guess is the error is due to user permissions not able to open or modify the uninstaller.**

**Comment by arkakkar** [comment]
Also to mention works fine after restarting the system. The uninstaller.exe does not exist under file system maybe that's why we get this

<img width="603" alt="screen shot 2017-10-25 at 11 57 28 am" src="https://user-images.githubusercontent.com/13099382/31989193-30cb9172-b98f-11e7-9155-27444a7c539a.png">

So all in all, sometimes when installing/updating app when a previous version is already installed,  the process does not clear the old uninstall cleanly.

**Comment by develar** [comment]
Fixed. `Copy` changed to `Rename` because old uninstaller in any case will be deleted. So, it allows us to be sure that Windows will not lock old uninstaller file for some reason.

**Comment by arkakkar** [comment]
I tried changing the code in installer.nsh file since you did not publish the fix. The issue is though still happening

**Comment by arkakkar** [comment]
The issue still happens for one particular user and we don't yet know if its happening for any others. Could it be something machine specific. The issue is that the new installer isn't able to uninstall previous version files completely
