### ISSUE TITLE
AppImage autoupdates: sha512 checksum mismatch error

### ISSUE THREAD

**Issue by akashnimare** [electron-userland/electron-builder#2947]
I'm getting the following error on AppImage -

Builder configuration for version which is trying to update -
> app version: [v2.0.0](https://github.com/zulip/zulip-electron/releases/tag/v2.0.0)
electron-builder: v20.8.1 
electron-updater: v2.21.4

Builder configuration for latest release -
> app version: [v2.3.1](https://github.com/zulip/zulip-electron/releases/tag/v2.3.1)
electron-builder: v20.13.4
electron-updater: v2.21.10

```sh
[2018-05-24 22:58:15:0459] [info] Checking for update
[2018-05-24 22:58:29:0128] [info] Found version 2.3.1 (url: Zulip-2.3.1-x86_64.AppImage)
[2018-05-24 22:58:29:0129] [info] Downloading update from Zulip-2.3.1-x86_64.AppImage
[2018-05-24 22:58:29:0164] [info] No cached update available
[2018-05-24 22:58:31:0078] [error] Cannot download differentially, fallback to full download: Error: invalid code lengths set
    at InflateRaw.zlibOnError (zlib.js:152:15)
From previous event:
    at readBlockMap (/tmp/.mount_Zulip-b5BFOs/app/resources/app.asar/node_modules/electron-updater/src/differentialDownloader/DifferentialDownloader.ts:224:28)
    at FileWithEmbeddedBlockMapDifferentialDownloader.download (/tmp/.mount_Zulip-b5BFOs/app/resources/app.asar/node_modules/electron-updater/src/differentialDownloader/FileWithEmbeddedBlockMapDifferentialDownloader.ts:10:31)
    at <anonymous>
[2018-05-24 22:59:53:0425] [error] Error: Error: sha512 checksum mismatch, expected HHDt+ZTPF4HRT/hi18gzivF6+5FQEhog3tcyVIzzS3y1WIonvhaUTaACUE9Gn3cdbgyG33Zx6AxM28VIvYU7eQ==, got kRI3WciD97vsiS8eLFs+U5y++B0Pby5sHGdfX9Z7ZzIbfP8xsWxd31NK2zzGaGvRoEgXaEl5L/EayyeHqdKBuA==
    at newError (/tmp/.mount_Zulip-b5BFOs/app/resources/app.asar/node_modules/builder-util-runtime/src/index.ts:23:17)
    at DigestTransform.validate (/tmp/.mount_Zulip-b5BFOs/app/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:283:13)
    at DigestTransform._flush (/tmp/.mount_Zulip-b5BFOs/app/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:266:14)
    at DigestTransform.prefinish (_stream_transform.js:137:10)
    at emitNone (events.js:105:13)
    at DigestTransform.emit (events.js:207:7)
    at prefinish (_stream_writable.js:576:14)
    at finishMaybe (_stream_writable.js:584:5)
    at endWritable (_stream_writable.js:595:3)
    at DigestTransform.Writable.end (_stream_writable.js:546:5)
    at IncomingMessage.onend (_stream_readable.js:584:10)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
From previous event:
    at CancellationToken.createPromise (/tmp/.mount_Zulip-b5BFOs/app/resources/app.asar/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.download (/tmp/.mount_Zulip-b5BFOs/app/resources/app.asar/node_modules/electron-updater/src/electronHttpExecutor.ts:19:44)
    at task (/tmp/.mount_Zulip-b5BFOs/app/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:78:35)
    at <anonymous>

```

**Comment by faizalluthfi** [comment]
I am facing the same problem. Are you still facing this problem now?

**Comment by vifird** [comment]
Resolved? I have the same problem? Reopen it ?

**Comment by Pandakls** [comment]
Same problem here. Using the classique options for electron builder an receiving this kind of stack randomely among my app updates: 

sha512 checksum mismatch, expected
at newError (/tmp/resources/app.asar/node_modules/builder-util-runtime/src/index.ts:29:17)
    at DigestTransform.validate (/tmp/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:378:13)
    at DigestTransform._flush (/tmp/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:361:14)
    at DigestTransform.prefinish (_stream_transform.js:141:10)
    at DigestTransform.emit (events.js:182:13)
    at DigestTransform.EventEmitter.emit (domain.js:442:20)
    at prefinish (_stream_writable.js:630:14)
    at finishMaybe (_stream_writable.js:638:5)
    at endWritable (_stream_writable.js:649:3)
    at DigestTransform.Writable.end (_stream_writable.js:589:5)
    at IncomingMessage.onend (_stream_readable.js:634:10)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at ElectronHttpExecutor.download (/tmp/resources/app.asar/node_modules/electron-updater/src/electronHttpExecutor.ts:23:73)
    at Object. (/tmp/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:62:35)
    at Generator.throw ()
From previous event:
    at Object.task (/tmp/resources/app.asar/node_modules/electron-upda
    at /tmp/resources/app.asar/node_modules/electron-updater/src/AppUp
From previous event:
    at AppImageUpdater.executeDownload (/tmp/resources/app.asar/node_m
8)
    at AppImageUpdater.executeDownload (/tmp/resources/app.asar/node_m
8)
    at AppImageUpdater.doDownloadUpdate (/tmp/resources/app.asar/node_
:33:17)
    at AppImageUpdater.downloadUpdate (/tmp/resources/app.asar/node_mo
)
    at /tmp/resources/app.asar/node_modules/electron-updater/src/AppUp
    at Generator.next ()
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)

**Comment by Pandakls** [comment]
Still the same problem after updating to :

"electron-builder": "21.2.0",
"electron-updater": "4.1.2",

**Comment by alexandermckay** [comment]
I also have this problem. @Pandakls how did you fix it ?

**Comment by Pandakls** [comment]
Actually, when the server is making a new update (with new checksum) the client was getting the new checksum detecting the uptade. But when asking the server it's the old version that was still delivered. So i forced clear server cache on each update so it wasn't incoherent anymore.
