### ISSUE TITLE
AppImage started failing when file association contains multiple extensions

### ISSUE THREAD

**Issue by lutzroeder** [electron-userland/electron-builder#3204]
* **Version**: 20.26.1
* **Target**: Linux/AppImage

`npx electron-builder --linux` started failing when `electron-builder.yml` or `package.json` contains multiple file extensions for a single association. Works when building `--mac` and `--win`.

```
  ⨯ appimage.AppImageConfiguration.FileAssociations: []appimage.FileAssociation: appimage.FileAssociation.Ext: ReadString: expects " or n, but found [, error found in #10 byte of ...|t","ext":["txt","doc|..., bigger context ...|6}],"fileAssociations":[{"name":"Document","ext":["txt","doc"]}]}|...
```

Simple repro: [repro3204.zip](https://github.com/electron-userland/electron-builder/files/2259230/repro3204.zip)

**Comment by lutzroeder** [comment]
@develar, @AdrianoFerrari, is this a recent regression in AppImage file extension support?

**Comment by AdrianoFerrari** [comment]
First impressions, @lutzroeder :
As far as I can tell `FileAssociation` should contain both a `name` and an `ext`, for _each_ entry. So it should probably be:
```
[{"name":"Document","ext":"txt"}, {"name":"Document", "ext": "doc"}]
```
Or in YAML:
```
fileAssociations:
  - name: Document
    ext: txt
  - name: Document
    ext: doc
```

Seems to run OK when I do that (well, except for other package.json complains like missing author email).

Not sure why that would have worked with `--mac` and `--win` though...

**Comment by lutzroeder** [comment]
Makes sense and thank you for looking into this. Guess it should either turn into a breaking change allowing only one extension per association and Win/Mac should flag arrays as an error as well or it should be fixed for `AppImage`.

**Comment by fxha** [comment]
This issue is still not fixed. Any progress here or wontfix but please update the documentation if so?

**Comment by fxha** [comment]
There is another problem associated with the workaround @AdrianoFerrari mentioned. The workaround also fails when using the same icon for more than one entry on macOS.

- Multiple extension in one entry result in an error on Linux: [log](https://travis-ci.org/marktext/marktext/jobs/518908730#L3674)
- Using multiple entries but same icon result in an error on macOS: [log](https://travis-ci.org/marktext/marktext/jobs/518933794#L3256)

**Comment by ollm** [comment]
This error is still present when build AppImage in the current version of electron-builder (22.3.1)

This is the error you are currently giving:

```
⨯ appimage.AppImageConfiguration.FileAssociations: []appimage.FileAssociation: appimage.FileAssociation.Ext: ReadString: expects " or n, but found [, error found in #10 byte of ...|G","ext":["jpg","jpe|..., bigger context ...|eAssociations":[{"description":"Image JPG","ext":["jpg","jpeg","jif","jfi","jfif","jfif-tbnl","jpe"]|...  
⨯ /my-app-dir/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
           Error: /my-app-dir/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
               at ChildProcess.<anonymous> (/my-app-dir/node_modules/builder-util/src/util.ts:239:14)
               at Object.onceWrapper (events.js:313:26)
               at ChildProcess.emit (events.js:223:5)
               at maybeClose (internal/child_process.js:1021:16)
               at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

For example, this works
```
"fileAssociations": [
	{
		"description": "Image JPG",
		"ext": "jpg",
		"role": "Viewer"
	}
]
```
But this gives error
```
"fileAssociations": [
	{
		"description": "Image JPG",
		"ext": [
			"jpg",
			"jpeg",
			"jif",
			"jfi",
			"jfif",
			"jfif-tbnl",
			"jpe"
		],
		"role": "Viewer"
	}
]
```

**Comment by Kilian** [comment]
as of 22.11.8 this is still an issue.

**Comment by arantes555** [comment]
Also still having the same issue.

**Comment by AlanSean** [comment]
as of 22.13.1 this is still an issue.
