### ISSUE TITLE
Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by kspearrin** [electron-userland/electron-builder#3459]
* **Version**: ^20.31.2

* **Target**: --win --x64 --ia32

I just updated to ^20.31.2 and updater 3.1.6. Trying to build the project now throws:

> node_modules/builder-util-runtime/out/httpExecutor.d.ts:25:39 - error TS1039: Initializers are not allowed in ambient contexts.

**Comment by public-virtualys** [comment]
We just encounter the same problem in an electron+angular project.
Resolved by upgrading typescript to 3.1.6 (and angular to 7.0.3).

**Comment by snipter** [comment]
Resolved by upgrading `typescript` to `3.1.6`

**Comment by kspearrin** [comment]
@develar This is still a problem with 2.x versions of TypeScript and latest updater/builder versions.
