### ISSUE TITLE
Building for Windows Error

### ISSUE THREAD

**Issue by L3V147H4N** [electron-userland/electron-builder#366]
```

electron-sample@0.0.1 dist D:\electron
build

license in the development package.json is deprecated, please move to the application package.json
Rebuilding app dependencies for arch ia32 to D:\electron\app
Removing D:\electron\dist\win
Packaging app for platform win32 ia32 using electron v0.37.7
Error: D:\electron\node_modules\electron-winstaller-fixed\vendor\Update.com failed with exit code: 4294967295
    at ChildProcess.<anonymous> (D:\electron\node_modules\electron-winstaller-fixed\lib\spawn-promise.js:33:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at tsAwaiter (D:\electron\node_modules\electron-builder\src\awaiter.ts:10:51)
    at Object.build (D:\electron\node_modules\electron-builder\src\builder.ts:30:59)
    at Object.<anonymous> (D:\electron\node_modules\electron-builder\src\build-cli.ts:47:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! electron-sample@0.0.1 dist: `build`
npm ERR! Exit status 4294967295
`
```

**Comment by develar** [comment]
Is your windows 32 or 64 bit? Please  specify electron-builder version. 

Set `DEBUG=electron-windows-installer` to get debug logs.

**Comment by L3V147H4N** [comment]
Im using WIndows 10 Pro x64 and electron-builder 3.12.0

**Comment by develar** [comment]
@L3V147H4N Please try v3.11.0 (it is a previous version, yes). It seems it is corrupted Update.exe (well, our CI tests passed). Please also attach logs.

**Comment by L3V147H4N** [comment]
Now it packs everything with no errors but it seems that is not including node_modules, maybe I got it wrong, the dependency modules need to be in the same directory as my app?

this is my structure:

![image](https://cloud.githubusercontent.com/assets/5846479/14886980/154bc7cc-0d2a-11e6-9fa7-2ec39b52ad7e.png)

**Comment by L3V147H4N** [comment]
im running build on the electron dir

**Comment by L3V147H4N** [comment]
I moved the proyect dependencies to the app folder: (just nconf)

```
> electron-sample@0.0.1 pack D:\electron
> build

license in the development package.json is deprecated, please move to the application package.json
Rebuilding app dependencies for arch ia32 to D:\electron\app
nconf@0.8.4 D:\electron\app\node_modules\nconf
async@1.5.2 D:\electron\app\node_modules\async
ini@1.3.4 D:\electron\app\node_modules\ini
secure-keys@1.0.0 D:\electron\app\node_modules\secure-keys
yargs@3.32.0 D:\electron\app\node_modules\yargs
camelcase@2.1.1 D:\electron\app\node_modules\camelcase
cliui@3.2.0 D:\electron\app\node_modules\cliui
string-width@1.0.1 D:\electron\app\node_modules\string-width
code-point-at@1.0.0 D:\electron\app\node_modules\code-point-at
number-is-nan@1.0.0 D:\electron\app\node_modules\number-is-nan
is-fullwidth-code-point@1.0.0 D:\electron\app\node_modules\is-fullwidth-code-point
strip-ansi@3.0.1 D:\electron\app\node_modules\strip-ansi
ansi-regex@2.0.0 D:\electron\app\node_modules\ansi-regex
wrap-ansi@2.0.0 D:\electron\app\node_modules\wrap-ansi
decamelize@1.2.0 D:\electron\app\node_modules\decamelize
os-locale@1.4.0 D:\electron\app\node_modules\os-locale
lcid@1.0.0 D:\electron\app\node_modules\lcid
invert-kv@1.0.0 D:\electron\app\node_modules\invert-kv
window-size@0.1.4 D:\electron\app\node_modules\window-size
y18n@3.2.1 D:\electron\app\node_modules\y18n
Packaging app for platform win32 ia32 using electron v0.37.7
```

After that I get an .exe but when I ran it just a blank widow, no errors.. nothing, just a blank window

**Comment by develar** [comment]
@L3V147H4N `node_modules` in the root of project only for dev dependencies. App should be in the `app/node_modules`.

Please let's solve first problem —does 3.13 works for you? After that I will help you to fix second issue. Because it is very important to understand that 3.13 is ok.

**Comment by L3V147H4N** [comment]
no, I did npm i electron-builder@3.11.0 and then ran it, that yielded the logs I posted above

**Comment by caibirdme** [comment]
Got a similar error.
My project structure can be found in #371
When I build on mac everything will be fine,but reported error when building on windows(win7 64) machine.

The first problem is that I can't even run the app directly on windows because of sqlite3.when I run `electron-rebuild` to rebuild sqlite3,it creates a `electron-v0.37-win32-x64` in `app/node_modules/sqlite3/lib/binding`  .I have to rename `electron-v0.37-win32-x64` to `node-v47-win32-x64` so can I run the app by running`./node_modules/.bin/electron .` or it will emit an error.
 
The second problem is that When I build on windows machine there's an error.
```
tweetnacl@0.13.3 D:\TOEFL-PC\app\node_modules\tweetnacl
Removing D:\TOEFL-PC\dist\win-x64
Packaging app for platform win32 x64 using electron v0.37.8
System.Xml.XmlException: '=' is an unexpected token. The expected token is ';Line 9, position 71.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1tring expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributlue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, 32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvid Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleasePackage.get_SuggestedReleaseFileName()
   at Squirrel.Update.Program.ReleasifyElectron(String package, String target, String packagesDir, String bootstrapperExe, String backgroundGif, String singOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
Error: D:\TOEFL-PC\node_modules\electron-winstaller-fixed\vendor\Update.com fed with exit code: 4294967295
    at ChildProcess.<anonymous> (D:\TOEFL-PC\node_modules\electron-winstallerxed\lib\spawn-promise.js:33:16)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at spawn (D:\TOEFL-PC\node_modules\electron-winstaller-fixed\lib\spawn-prse.js:22:10)
    at D:\TOEFL-PC\node_modules\electron-winstaller-fixed\lib\index.js:168:38
    at [object Generator].next (native)
From previous event:
    at releasify (D:\TOEFL-PC\node_modules\electron-winstaller-fixed\lib\indes:171:16)
    at Object.<anonymous> (D:\TOEFL-PC\node_modules\electron-winstaller-fixedb\index.js:94:11)
From previous event:
    at Object.createWindowsInstaller (D:\TOEFL-PC\node_modules\electron-winster-fixed\lib\index.js:118:16)
    at WinPackager.<anonymous> (D:\TOEFL-PC\node_modules\electron-builder\srcnPackager.ts:161:48)
    at [object Generator].next (native)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at tsAwaiter (D:\TOEFL-PC\node_modules\electron-builder\src\awaiter.ts:10)
    at Object.build (D:\TOEFL-PC\node_modules\electron-builder\src\builder.ts:59)
    at Object.<anonymous> (D:\TOEFL-PC\node_modules\electron-builder\src\builli.ts:47:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejnode_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! @ build: `build`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the @ build script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project wit
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\TOEFL-PC\npm-debug.log
```
I don't know how to fix it.I just want to build a .exe this time and don't expect autoUpdate, do I need handle `Windows.Squarriel`? if yes, I `npm install electron-squirrel-startup` and required it at the top of my index.js, is it Okay?

node version 5.10.0
npm version 3.8.3
electron version 0.37.8
electron-builder version 3.17.1

**Comment by framerate** [comment]
I'm seeing this `Update.com` error as well when trying to build on windows. `npm run dist`

**Comment by gamestailer94** [comment]
if you have an & in your Win IconUrl, it kills the xml parser, try using github for the url, then it schould work

**Comment by develar** [comment]
I think it is fixed in the 3.26.1.

**Comment by RyanFarley** [comment]
I am still getting this same error with electron-builder 3.27.0 on Windows 10 x64 doing a build for Win x64. 

`Error: C:\Developer\TimeLogger\node_modules\electron-builder\node_modules\electron-winstaller-fixed\vendor\Update.com failed with exit code: 4294967295`

Any other details I can provide?

**Comment by develar** [comment]
@RyanFarley Please attach `node_modules/electron-winstaller-fixed/vendor/SquirrelSetup.log`. And set `DEBUG=electron-windows-installer` to get debug logs.

**Comment by RyanFarley** [comment]
This is the log http://pastebin.com/raw/HmyGECrk

**Comment by develar** [comment]
@RyanFarley Why temp dir is used, did you set custom dist out? Please set `DEBUG=electron-windows-installer` and run build again to get debug console out.

**Comment by RyanFarley** [comment]
I have no idea why temp dir is being used. I did set a output folder to "dist" (which I believe is the default so I suppose I could just omit that). 

I removed the output directory and ran again with same result. This is the console output: http://pastebin.com/raw/Pb0KXmeS

**Comment by develar** [comment]
@RyanFarley Are you sure that you need to build MSI?

**Comment by RyanFarley** [comment]
Well, I would like to distribute as an MSI if possible. If I can't create the MSI, would I just distribute the packed setup executable that is created? Does that create application shortcuts and install itself into AppData\local or somewhere? Is that correct?

**Comment by develar** [comment]
@RyanFarley https://github.com/electron/windows-installer/issues/40#issuecomment-198744879 MSI only for corporate massive deployments. 

> Does that create application shortcuts and install itself into AppData\local or somewhere? Is that correct?

Squirrel.Window app will be generated. To create shortcuts — 

> .exe and -ia32.exe: Windows installer, required for Windows user to initial install. Please note — your app must handle Squirrel.Windows events. See real example.

in the readme. See https://github.com/electron/windows-installer#handling-squirrel-events

**Comment by RyanFarley** [comment]
Ah, right. I remember reading that now. I'll review that and go the route of skipping the MSI. Thanks for the help.
