### ISSUE TITLE
error output:wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"

### ISSUE THREAD

**Issue by christianbundy** [electron-userland/electron-builder#3830]
* **Version**: 20.39.0

* **Target**: AppImage

```
path: /usr/bin/wine
args: wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.4.0/rcedit-ia32.exe /project/dist/win-unpacked/Patchwork.exe --set-version-string FileDescription Patchwork --set-version-string ProductName Patchwork --set-version-string LegalCopyright Copyright © 2019 Secure Scuttlebutt Consortium --set-file-version 3.12.0-dev --set-product-version 3.12.0.0 --set-version-string InternalName Patchwork --set-version-string OriginalFilename  --set-version-string CompanyName Secure Scuttlebutt Consortium
output: 
error output:wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0023:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0023:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0023:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0023:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0023:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
001f:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
001f:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
001f:err:mshtml:check_version Could not open VERSION file
0029:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0029:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
001f:err:mshtml:check_version Could not open VERSION file
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.wine' has been updated.

github.com/develar/app-builder/pkg/util.Execute
	/Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:105
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.12/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12/libexec/src/runtime/asm_amd64.s:1337

Error: /project/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/project/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:285:13)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
From previous event:
    at processImmediate (timers.js:637:19)
From previous event:
    at WinPackager.signAndEditResources (/project/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/project/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/project/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at /project/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/project/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /project/node_modules/app-builder-lib/src/platformPackager.ts:250:16
From previous event:
    at WinPackager.doPack (/project/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /project/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/project/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /project/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:637:19)
From previous event:
    at Packager.doBuild (/project/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /project/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /project/node_modules/graceful-fs/graceful-fs.js:111:16
    at /project/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at Packager._build (/project/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /project/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:637:19)
From previous event:
    at Packager.build (/project/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/project/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/project/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/project/node_modules/electron-builder/src/cli/cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssb-patchwork@3.12.0-dev release: `electron-builder "--linux" "--win"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-patchwork@3.12.0-dev release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-16T02_48_44_168Z-debug.log
```

**Comment by polofgrs** [comment]
**Same here :**
Using gitlab-CI :

`.gitlab-ci.yml` :
```yaml
  image: electronuserland/builder:wine
  script:
    - yarn install
    - yarn add electron-builder --dev
    - ./node_modules/.bin/electron-builder --win
```
`package.json` :
```json
...
"build": {
    "appId": "calendar-web-app",
    "files": [
      "**/*",
      "dist/**/*"
    ],
    "directories": {
      "output": "releases",
      "buildResources": "dist"
    },
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ]
    },
    "win": {
      "target": "nsis"
    }
  }
```
Gitlab-CI job output : 
```
$ ./node_modules/.bin/electron-builder --win
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • artifacts will be published if draft release exists reason=CI detected
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=4.1.4 appOutDir=releases/win-unpacked
  • downloading               parts=8 size=61 MB url=https://github.com/electron/electron/releases/download/v4.1.4/electron-v4.1.4-win32-x64.zip
  • downloaded                duration=21.053s url=https://github.com/electron/electron/releases/download/v4.1.4/electron-v4.1.4-win32-x64.zip
  • default Electron icon is used reason=application icon is not set
  • downloading               parts=1 size=5.6 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  • downloaded                duration=2.056s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  ⨯ error: signal: killed
path: /usr/bin/wine
args: wine /root/.cache/electron-builder/winCodeSign/winCodeSign-2.4.0/rcedit-ia32.exe /builds/arrowdynamics/calendar_web_app/fullWebApp/releases/win-unpacked/full-web-app.exe --set-version-string FileDescription full-web-app --set-version-string ProductName full-web-app --set-version-string LegalCopyright Copyright © 2019 ArrowDynamics --set-file-version 0.0.0 --set-product-version 0.0.0.0 --set-version-string InternalName full-web-app --set-version-string OriginalFilename  --set-version-string CompanyName ArrowDynamics
output: 
error output:wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
001f:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
001f:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0023:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0023:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0023:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0023:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0023:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
001f:err:mshtml:check_version Could not open VERSION file
0029:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0029:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
001f:err:mshtml:check_version Could not open VERSION file
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/root/.wine' has been updated.

github.com/develar/app-builder/pkg/util.Execute
	/Volumes/data/Documents/app-builder/pkg/util/util.go:75
github.com/develar/app-builder/pkg/wine.execWine
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:105
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:78
runtime.main
	/usr/local/Cellar/go/1.12/libexec/src/runtime/proc.go:200
runtime.goexit
	/usr/local/Cellar/go/1.12/libexec/src/runtime/asm_amd64.s:1337

Error: /builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:285:13)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
From previous event:
    at processImmediate (timers.js:637:19)
From previous event:
    at WinPackager.signAndEditResources (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/winPackager.ts:363:21)
    at go$readdir$cb (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at /builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/winPackager.ts:355:73)
    at /builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:637:19)
From previous event:
    at WinPackager.doPack (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/platformPackager.ts:167:165)
    at /builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at Packager.doBuild (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/packager.ts:366:57
From previous event:
    at Packager._build (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:637:19)
From previous event:
    at Packager.build (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/builds/arrowdynamics/calendar_web_app/fullWebApp/node_modules/electron-builder/src/cli/cli.ts:46:19)
ERROR: Job failed: exit code 1
```

**Fix :**
Retrying the job on the gitlab CI/CD tab fixed the issue in the next run : 
```
$ ./node_modules/.bin/electron-builder --win
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • artifacts will be published if draft release exists reason=CI detected
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=4.1.4 appOutDir=releases/win-unpacked
  • downloading               parts=8 size=61 MB url=https://github.com/electron/electron/releases/download/v4.1.4/electron-v4.1.4-win32-x64.zip
  • downloaded                duration=31.851s url=https://github.com/electron/electron/releases/download/v4.1.4/electron-v4.1.4-win32-x64.zip
  • default Electron icon is used reason=application icon is not set
  • downloading               parts=1 size=5.6 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  • downloaded                duration=1.737s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  • building        target=nsis file=releases/full-web-app Setup 0.0.0.exe archs=x64 oneClick=true perMachine=false
  • downloading               parts=1 size=1.4 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.2/nsis-3.0.3.2.7z
  • downloaded                duration=2.419s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.3.2/nsis-3.0.3.2.7z
  • downloading               parts=1 size=1.0 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z
  • downloaded                duration=1.663s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z
  • building block map blockMapFile=releases/full-web-app Setup 0.0.0.exe.blockmap
Job succeeded
```
Would there be a more permanent fix ?

**Comment by christianbundy** [comment]
Retrying also resolved the issue for me on Travis CI, I'm unclear on why.

**Comment by jreinert** [comment]
Retrying only works some times. We had to set retries to 2 for it to build most of the time. It seems that wine wants to display some window. Most likely a confirmation dialog or something else that waits for user input because if i use `xvfb` to pretend i have an x server running the error is gone but it never finishes the build and just blocks forever.

**Comment by offaxis** [comment]
Hi !

I have this error on trying to package for Windows on Mac !

Any updates on this error ?

**Comment by MortezaAghili** [comment]
Same here... any updates?

**Comment by concuacon** [comment]
Same here... any updates?

**Comment by huangzonggui** [comment]
Hi !
I have this error on trying to package for Windows on Mac !
 any updates?

**Comment by BillGHero** [comment]
I've been seeing this on Ubuntu 18.04.2 as well.

**Comment by mikekok** [comment]
Same goes for me, trying to package for Windows using Elementary OS.

**Comment by woxixiulayin** [comment]
remove MSI out of target will help

**Comment by offaxis** [comment]
Check your ressources icons too ! Windows seems to be very picky on icons size !

**Comment by kanjieater** [comment]
Getting this inside my docker container when building for windows

**Comment by wduminy** [comment]
@kanjieater I fixed this problem by upgrading to electron builder version 22.2

**Comment by kanjieater** [comment]
```
electron-builder@^22.2.0:
  version "22.2.0"
  resolved "https://registry.yarnpkg.com/electron-builder/-/electron-builder-22.2.0.tgz#f7244b4c92bb5c7323db88f3fb9a22e0ca6cf8a0"
```
Updated but still getting the same thing.
 ```
wine "/root/.wine/drive_c/Program Files/app Setup 0.0.1.exe"
000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
```
Runnig this from my dockerfile
```
ENV DISPLAY :99
RUN Xvfb $DISPLAY -screen 0 1920x1080x24 > /dev/null 2>&1 &
wine "/root/.wine/drive_c/Program Files/app Setup 0.0.1.exe" & yarn wait-port 8182 && yarn cypress run --config video=false
```

Can we reopen? Anyone have a working dockerfile?

**Comment by wduminy** [comment]
@kanjieater On Mac-OS Catalina my build now works _natively_.  I stopped using the docker file.  Perhaps better to log a new issue - I am not sure that chatting on closed issues helps :-).

**Comment by Brutia** [comment]
On my side, I solved this problem by using docker image electronuserland/builder:wine-mono instead of electronuserland/builder:wine

**Comment by worudso** [comment]
try
```shell
docker system prune -a -f
```
I don't know why, but it worked. Perhaps it was because of the shortage of disk space. It was 99% occupied before I ran that command.

**Comment by tsyopa** [comment]
Removing electron-builder cache folder helped in my case.

For me the cache folder was located in `~/Library/Caches/electron-builder`
According to your logs this folder is located in `/root/.cache/electron-builder`

**Comment by itsPG** [comment]
same issue occurred while building msi target on macOS 10.14.5

electron-builder version: 22.8.0

**Comment by itsPG** [comment]
Solved this issue by adding icon for msi.

For anyone who's lead here by google search:

> output:wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"

is a common error msg that is not really helpful.

You may need to dig the error msg out carefully.

**Comment by AtFreezingPoint** [comment]
Still not solved, getting it on Arch trying to run Fivem for GTA.

**Comment by ifedapoolarewaju** [comment]
sharing for anyone who might find it helpful as well: I fixed this issue when running on my Mac by properly generating my `icon.ico` file

**Comment by LeyiZhou** [comment]
> 

Amazing!!! item works for me

**Comment by LeyiZhou** [comment]
> sharing for anyone who might find it helpful as well: I fixed this issue when running on my Mac by properly generating my `icon.ico` file

Amazing!!! it works for me!
