### ISSUE TITLE
Cannot compute electron version from installed node modules - none of the possible electron modules are installed.

### ISSUE THREAD

**Issue by eugeneblog** [electron-userland/electron-builder#4157]
* **Version**: 

* **Target**:

**Comment by alibosworth** [comment]
@eugeneblog your report seems to be missing some information

**Comment by miguelyoobic95** [comment]
Hi, we are facing an issue with the same error message. I have electron and electron builder installed locally, and somehow this is happening. I can specify the version of Electron to make it work but it should not be necessary ... Additionally, I get an error message when it does run that is impossible to read on my terminal as it has a lot of newlines which are breaking the text.

![image](https://user-images.githubusercontent.com/35100759/63280808-64510580-c2a3-11e9-8fb6-9ddcc63534ae.png)

![image](https://user-images.githubusercontent.com/35100759/63280845-729f2180-c2a3-11e9-9471-cd3592070472.png)

**Comment by JeffreyDevloo** [comment]
I had the same problem with electron builder versions 21.x
I reverted back to builder version 20.28.4 to temporarily resolver the issue.
Not working:
```
npx electron-builder build --linux
npx: installed 179 in 10.314s
  • electron-builder  version=21.2.0 os=4.18.0-25-generic
  • loaded configuration  file=package.json ("build" field)
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed.

```
Working:
```
npx electron-builder@20.28.4 build --linux
npx: installed 194 in 11.601s
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=<path_to_dist_builder_packages>/builder-effective-config.yaml
  • skipped app dependencies rebuild reason=npmRebuild is set to false
```

**Comment by miguelyoobic95** [comment]
I can confirm that reverting also immediately solves the issue for us too :)

**Comment by miguelyoobic95** [comment]
any updates on this one ?

**Comment by matheo** [comment]
The referred issue #3984 is not a solution. I'm getting
```
  • electron-builder  version=21.2.0 os=5.0.0-27-generic
  • loaded configuration  file=package.json ("build" field)
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^6.0.7") is not fixed in project.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
```
and my yarn.lock does have
```
electron@^6.0.7:
  version "6.0.8"
```
I'm building the app on a subfolder with:
```
electron-builder --project ./dist/apps/electron
```
There's my yarn.lock and my package.json with
```

  "files": [
    "**/*",
    "build/icon.*",
    "build/icons"
  ],
  "dependencies": {
    "@sendgrid/mail": "^6.4.0",
    "draggabilly": "2.2.0",
    "node-fetch": "^2.6.0",
    "plivo": "^4.1.3",
    "source-map-support": "^0.5.12",
    "stripe": "~7.8.0",
    "tslib": "^1.9.0"
  },
  "devDependencies": {
    "electron": "^6.0.7"
  }
```

The parser just accepts `6.0.8` and not `^6.0.7`

**Comment by miguelyoobic95** [comment]
I can confirm we still have the issue and rolling back or passing the electron version to electron-builder directly fixes the problem for the time being :)

**Comment by YannickFricke** [comment]
Still applies
Switched back to version 20 works for me

It seems that electron builder has an error while trying to read the semver version of electron in 21

**Comment by AndreaMaffe** [comment]
I had the same issue and i solved it in this way:

1. run `electron -v ` in the terminal

`--> v7.1.8`  (example)

2. go to `package.json` and insert `"electron": "<your version>"`  e.g. `"electron": "7.1.8"`

**Comment by skorunka** [comment]
As @AndreaMaffe pointed out. It is required to have `electron` in `devDependencies` in the `package.json` file in the directory one tries to build.

**Comment by vazra** [comment]
Yes, the workaround for the time being is using the electron version specifically 

in the package.json changing from `"electron": "^8.1.0",` to `"electron": "8.1.0"` will fix the issue.

**Comment by Amethystafyy282** [comment]
I fixed this problem by removing the "^" in package.json
Before :     "electron": "^10.1.3",
After:     "electron": "10.1.3",

**Comment by Teomazivila** [comment]
Hello, I am still facing this issue even after applying all the recommended changes on this post!

yarn dist
yarn run v1.22.10
$ electron-builder
  • electron-builder  version=22.9.1 os=10.0.19042
  • loaded configuration  file=package.json ("build" field)
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Here is my package.json** 

devDependencies": {
        "electron-builder": "20.28.4",
        "less": "^3.11.3",
        "less-loader": "^6.1.0",
        "ts-loader": "^7.0.5"
    },
    "build":{
        "appId":"my.id.app",
        "productName":"MyApp",
        "target":"nsisWEB",
        "directories":{
            "output": "dist"
        },
        "nsisWeb":{
            "allowToChangeInstallationDirectory":false,
            "oneClick": false,
            "perMachine":true,
            "installerIcon":"/public/cham_logo_T8R_icon.ico",
            "installerHeader":"/public/logo.bmp",
            "runAfterFinish": true,
            "createDesktopShortcut":true,
            "createStartMenuShortcut":true
        }

**Comment by do-kevin** [comment]
> Yes, the workaround for the time being is using the electron version precisely
> 
> in the package.json changing from `"electron": "^8.1.0",` to `"electron": "8.1.0"` will fix the issue.

This helped, thank you.
