### ISSUE TITLE
Why electron-builder sign mas/mas-dev app by Developer ID Application?

### ISSUE THREAD

**Issue by mahnunchik** [electron-userland/electron-builder#4960]
* **Version**: 22.6.0

* **Electron Version**: 8.2.5
* **Electron Type (current, beta, nightly)**: current

* **Target**: mas/mas-dev

Why electron-builder sign mas/mas-dev app by `Developer ID Application` certificate?

```
> app@1.0.0 dist /electron
> electron-builder "--mac" "mas-dev"

  • electron-builder  version=22.6.0 os=19.4.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=mas arch=x64 electron=8.2.5 appOutDir=dist/mas-dev
  • signing         file=dist/mas-dev/App.app identityName=Developer ID Application: Org (12345) identityHash=ABC provisioningProfile=none
  • signing         file=dist/mas-dev/App.app identityName=Mac Developer: Name (54321) identityHash=ABC provisioningProfile=/certs/macOS_App_Development.provisionprofile
```

It seems the first signing is unnecessary.

**Comment by patrickmichalina** [comment]
@mahnunchik agreed. I believe this is a bug. There is something off about the mac codesigning build settings.

**Comment by adam-lynch** [comment]
Duplicate of #4954 maybe?

**Comment by fedegratti** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/15077532/89712496-94d3f880-d967-11ea-97fd-9656d4d0d8da.png)

This is my config:
```
"mac": {
      "artifactName": "${productName}.${ext}",
      "category": "public.app-category.productivity",
      "icon": "assets/icon/mac/icon.icns",
      "hardenedRuntime": true,
      "gatekeeperAssess": false,
      "entitlements": "assets/entitlements.mac.plist",
      "entitlementsInherit": "assets/entitlements.mac.plist",
      "provisioningProfile": "assets/embedded.provisionprofile",
      "extendInfo": {
        "ITSAppUsesNonExemptEncryption": "NO"
      },
      "publish": [
        {
          "provider": "s3",
          "bucket": "xxx",
          "path": "xxx"
        }
      ],
      "target": [
        "mas"
      ]
},
"mas": {
      "provisioningProfile": "assets/embedded.provisionprofile",
      "entitlements": "assets/entitlements.mas.plist",
      "entitlementsInherit": "assets/entitlements.mas.inherit.plist",
      "binaries": [
        "/Users/fedegratti/Projects/compress/dist/mas/Compress.app/Contents/Resources/xxx"
      ]
},
"dmg": {
      "sign": false
}
```

Is there something wrong with my config?

A workaround that worked for me to let Apple happy, is to export (for backup) and remove the `Developer ID Application` certificate from Keychain before building. This is a kind of annoying solution for me since I build a signed `dmg` too, so I have to remove and add the certificate every build.

**Comment by mahnunchik** [comment]
![TKoNiRAJTeo](https://user-images.githubusercontent.com/780935/95649065-02bdad00-0adc-11eb-949e-55133caac881.jpg)

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4960#issuecomment-742144898

**Comment by idoodler** [comment]
Any update?

**Comment by MrMYHuang** [comment]
I tried and errors with 2 days for electron-builder 22.9.1 for building macOS notarized pkg, mas, and mas-dev targets. Finally, I find a great scheme to build the 3 targets without the deleting / adding certificates workaround.

* To notarize only pkg target, it needs individual electron-builder configuration files for all targets.
* To disable redundant code signing for mas and mas-dev targets, it needs to set mac target's "identity" to null!
I have a project using this scheme for your reference:
https://github.com/MrMYHuang/cbetar2/blob/7e299a7e480c27a21a19f121c7e70fd6e9668697/electronApps/package.json#L14-L17
https://github.com/MrMYHuang/cbetar2/blob/master/electronApps/mas.json
https://github.com/MrMYHuang/cbetar2/blob/master/electronApps/mac.json
https://github.com/MrMYHuang/cbetar2/blob/master/electronApps/masDev.json

However, one disadvantage of this scheme is there is no property sharing between configuration files. For example, you have to specify "files" property in each configuration.

**Comment by mifi** [comment]
I have the same problem. This is causing MAS app to crash when started with `Exception Type: EXC_CRASH (Code Signature Invalid)`...`Termination Reason: Namespace CODESIGNING, Code 0x1` etc.

I have a feeling this started happening after upgrading from 22.6.0 to 22.9.1, because I never had this crash before. Setting `identity` to `null` fixes the issue, thanks for reporting back!

with identity null:
```
  • skipped macOS code signing  reason=identity explicitly is set to null
  • skipped macOS code signing  reason=identity explicitly is set to null
  • signing         file=dist/mas/LosslessCut.app identityName=3rd Party Mac Developer Application: Mikael Finstad (...) identityHash=... provisioningProfile=....provisionprofile
```

without identity null:
```
  • signing         file=dist/mas/LosslessCut.app identityName=Developer ID Application: Mikael Finstad (...) identityHash=... provisioningProfile=none
  • signing         file=dist/mac/LosslessCut.app identityName=Developer ID Application: Mikael Finstad (...) identityHash=... provisioningProfile=none
  • signing         file=dist/mas/LosslessCut.app identityName=3rd Party Mac Developer Application: Mikael Finstad (...) identityHash=... provisioningProfile=....provisionprofile
```

**Comment by mmaietta** [comment]
Can you please try v22.10.5?

**Comment by csett86** [comment]
The duplicate signing with "Developer ID Application" and the real "3rd Party Mac Developer Application" for mas build is still present with v22.10.5, @mmaietta 

It thankfully does not fail if there is no "Developer ID Application" eg. on CI, but its still trying:

```
packaging       platform=mas arch=universal electron=12.0.2 appOutDir=dist/mas-universal
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                                1) F1D43C2053C729C08BFE5831377543363AA3DFB1 "3rd Party Mac Developer Installer: Hopp Foundation for Computer Literacy & Informatics gGmbH (UARN79NLDY)"
                                                2) 2F233ED24188A1CB4D827F2F43AB558137E507AB "3rd Party Mac Developer Application: Hopp Foundation for Computer Literacy & Informatics gGmbH (UARN79NLDY)"
                                                   2 identities found
                                              
                                                Valid identities only
                                                1) F1D43C2053C729C08BFE5831377543363AA3DFB1 "3rd Party Mac Developer Installer: Hopp Foundation for Computer Literacy & Informatics gGmbH (UARN79NLDY)"
                                                2) 2F233ED24188A1CB4D827F2F43AB558137E507AB "3rd Party Mac Developer Application: Hopp Foundation for Computer Literacy & Informatics gGmbH (UARN79NLDY)"
                                                   2 valid identities found
  • signing         file=dist/mas-universal/Digitales Klassenzimmer.app identityName=3rd Party Mac Developer Application: Hopp Foundation for Computer Literacy & Informatics gGmbH (UARN79NLDY) identityHash=2F233ED24188A1CB4D827F2F43AB558137E507AB provisioningProfile=embedded.provisionprofile
```

Full logs: https://github.com/HoppFoundation/jitsi-meet-electron/runs/2196597450?check_suite_focus=true

**Comment by mifi** [comment]
Update: the Code Signature Invalid crash when running app was not caused by this. It was because I was trying to run a mas build locally on my Mac, which I am 99% sure used to work fine last year, but now it doesnt. I’m guessing Apple changed something. Now to get it to run locally I have to use mas-dev and generate a development provisioning profile just for my computer and then make mas-dev use that instead. Then it starts, even though electron-builder signs it twice (first with «Developer ID Application», then 3rd party. So I guess it’s not a critical bug since it will just overwrite the first signature (thus taking more time to sign twice). I can also confirm same issue in 22.10.5

**Comment by mahnunchik** [comment]
https://github.com/electron-userland/electron-builder/issues/4960#issuecomment-853177468

**Comment by mifi** [comment]
i think this was fixed, but someone needs to test and verify

**Comment by woodcockjosh** [comment]
I am using electron-builder `22.11.7` and I can confirm this is still a problem.

**Comment by jediwade** [comment]
@woodcockjosh Would you mind sharing your package.json? I'm encountering the same problem and haven't figured out how to get a build to be signed with the 3rd party certs.

**Comment by mifi** [comment]
FWIW I'm also still seeing this (double signing), but still it successfully builds and I've successfully submitted to app store, so it doesn't really seem to be a problem.

https://github.com/mifi/lossless-cut/runs/4011140659?check_suite_focus=true
