### ISSUE TITLE
Icon is not showing correctly in task bar it is cutting in half until i pin the application in Windows

### ISSUE THREAD

**Issue by MuhammadHaseebAli** [electron-userland/electron-builder#5083]
"electron": "^9.0.2",
    "electron-builder": "^22.7.0"

Build configration
  "build": {
    "nsis": {
      "oneClick": true,
      "perMachine": false,
      "deleteAppDataOnUninstall": true
    },
    "win": {
      "publisherName": "Abc",
      "target": [
        "portable"
      ]
    },
    "extraResources": [
      {
        "from": "./config/config.json",
        "to": "config/config.json",
        "filter": [
          "**/*"
        ]
      }
    ],
    "directories": {
      "buildResources": "build"
    }
  },

**Comment by Rajdeep97** [comment]
@MuhammadHaseebAli 
I faced this problem and spent 1 full day not being able to figure out what to do.. I finally solved by this: https://github.com/electron-userland/electron-builder/issues/2128#issuecomment-411797743

You just have to create a png file of 256x256 size and explicitly mention it in the electron builder config.

**Comment by Venryx** [comment]
For me, even saving as a 256x256 image file did not fix the icon-cutoff issue.

What did fix it for me: resaving the 256x256 png file, in "8 bit" mode, with the default settings:
![](https://i.imgur.com/WBpT4Ci.png)
