### ISSUE TITLE
Dialog Box not displaying text properly for "strict" and "devmode" snaps

### ISSUE THREAD

**Issue by Melvin-Abraham** [electron-userland/electron-builder#5217]
* **Version**: v22.8.0
* **Electron Version**: v9.0.3
* **Electron Type (current, beta, nightly)**: current
* **Target**: Snap (on Ubuntu 20.04.1 LTS)

I am facing issues in terms of text rendering inside Dialogs when launching a strictly confined snap. The text to be displayed are plain ASCII characters but in **strict/devmode** snaps, I see that it renders the text as boxes instead of corresponding characters. This issue only occurs in **strict/devmode** snaps but not in **classic** snaps.

Also, the following warning is thrown in the console whenever this happens:

```
Gtk-Message: 11:34:28.960: GtkDialog mapped without a transient parent. This is discouraged.
```

Screenshots
-------------

### Strict/Devmode Snap

![electron dialog window with console warning: strict snap](https://user-images.githubusercontent.com/26056183/89755632-b36bf800-dafd-11ea-8198-a3040d1ac2ea.png)

![file dialog: strict snap](https://user-images.githubusercontent.com/26056183/89756594-a3094c80-db00-11ea-943c-f214fea0c5ef.png)

### Classic Snap

![electron dialog window: classic snap](https://user-images.githubusercontent.com/26056183/89755990-db0f9000-dafe-11ea-992b-7a00e5604f44.png)

![file dialog: classic snap](https://user-images.githubusercontent.com/26056183/89756433-1ced0600-db00-11ea-8e3b-a01de4609bed.png)

**Comment by hadisfr** [comment]
It seems to be related to `fontconfig`'s bug (See https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/18).

Try the workaround here: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/60
```bash
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by Melvin-Abraham** [comment]
@hadisfr Thanks a lot, that works like a charm... 👍

**Comment by topotech** [comment]
Why is this marked as closed?

**Comment by Rychu-Pawel** [comment]
Please reopen this issue. It is not fixed.
I'm having this issue with our app, which is run on Ubuntu 22.04 or higher. Lower Ubuntu versions don't have this issue.

**Comment by johannesjo** [comment]
Not sure if anybody ever reads these closed issues, we probably have to open up a new one.

**Comment by tan-dev-test** [comment]
Please reopen this issue. It is not fixed.
I'm having this issue with our app, which is run on Ubuntu 24.04, Lower Ubuntu versions don't have this issue.

**Comment by mikekreeki** [comment]
Same issue here.

**Comment by matonga** [comment]
Previous posters mention Ubuntu 22.04 and 24.04.

It is not working for me, Ubuntu 20.04 here¹. Also the fc-cache trick worked like a charm, though it says somewhere it is a temporary fix.

¹ yes I'm planning to migrate to Ubuntu 24.04 soon, and replace my HDD with an SSD

**Comment by Rychu-Pawel** [comment]
With the newest Electron version, the font issue is fixed for us on Ubuntu 22. I haven't tested any higher Ubuntu versions yet.

**Comment by cirras** [comment]
Please reopen this issue.
It's not resolved (even for `core22` and `core24` builds where it *should* be resolved due to the isolated font cache) and seems to be blocked by #8548.
