### ISSUE TITLE
32 bit + 64 bit installer

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#536]
OK this is quite needed for NSIS. I get no error at all after installing a 64-bit app on windows 32. (during install). But trying to open the app just nothing appears, no error either. Just nothing. So would be confusing to users. That's why a bundled installer probably is best.

**Comment by develar** [comment]
Required refactoring is already done, I am working on this.

**Comment by kunkinkan** [comment]
ok did something happen in one of the recent releases because my app just got 30MB bigger in size (the exe of the app, not installer)

**Comment by develar** [comment]
@kunkinkan Please compare asar files (`app.asar`).

**Comment by kunkinkan** [comment]
The app.asar is actually smaller in the newer version. But the "App Name.exe" (in Appdata/Local/Programs/App Name/App Name.exe") is 30MB bigger.

**Comment by develar** [comment]
@kunkinkan we don't modify exe — we only set icon and sign it. Please try latest electron version — my app size is the same as before.

**Comment by kunkinkan** [comment]
Now it's back to normal size, no idea what happened. Anyway this was off-topic, should I open another issue about 32+64 bit installer or can we keep this open ? (sorry!)

**Comment by develar** [comment]
Fixed as part: If installer contains only x64 package — error will be thrown.

**Comment by develar** [comment]
Size of installer: 59M. ia32 package 26M, x64 30MB. Solid? Well, no time. To investigate, will be not fixed for now.

**Comment by cyrus19901** [comment]
I am still facing the same issue. Where on building distribution for 64 bit I am getting 32 bit .Any solution to that ?

**Comment by Anil8753** [comment]
@cyrus19901, did you able to solve this issue. After building the package on 64-bit windows, I am getting a final executable and that is 32-bit.
