### ISSUE TITLE
Cannot find module 'dmg-license'

### ISSUE THREAD

**Issue by pranavwani** [electron-userland/electron-builder#6520]
* **Electron-Builder Version**: 22.14.5

* **Node Version**: v14.18.2

* **Electron Version**: v12.0.1
* **Electron Type (current, beta, nightly)**: current
 
* **Electron Update Version**: v4.6.1

* **Target**: dmg

**Stack**
```
⨯ Cannot find module 'dmg-license'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/dmg-builder/out/dmgLicense.js
- /usr/local/share/.config/yarn/global/node_modules/dmg-builder/out/dmg.js
- /usr/local/share/.config/yarn/global/node_modules/dmg-builder/out/dmgUtil.js
- /usr/local/share/.config/yarn/global/node_modules/app-builder-lib/out/macPackager.js
- /usr/local/share/.config/yarn/global/node_modules/app-builder-lib/out/packager.js
- /usr/local/share/.config/yarn/global/node_modules/app-builder-lib/out/index.js
- /usr/local/share/.config/yarn/global/node_modules/electron-builder/out/builder.js
- /usr/local/share/.config/yarn/global/node_modules/electron-builder/out/cli/cli.js
- /usr/local/share/.config/yarn/global/node_modules/electron-builder/cli.js  failedTask=build stackTrace=Error: Cannot find module 'dmg-license'
```

**Comment by robertpatrick** [comment]
@pranavwani `dmg-builder`, a component of `electron-builder`, declares an optional dependency on `dmg-license` so `yarn add electron-builder` should install it, as shown below.

```
% yarn add electron-builder --dev
yarn add v1.22.17
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 175 new dependencies.
info Direct dependencies
└─ electron-builder@22.14.5
info All dependencies
├─ @develar/schema-utils@2.6.5
├─ @electron/universal@1.0.5
├─ @malept/cross-spawn-promise@1.1.1
├─ @malept/flatpak-bundler@0.4.0
├─ @sindresorhus/is@0.14.0
├─ @szmarczak/http-timer@1.1.2
├─ @types/debug@4.1.7
├─ @types/glob@7.2.0
├─ @types/minimatch@3.0.5
├─ @types/ms@0.7.31
├─ @types/plist@3.0.2
├─ @types/verror@1.10.5
├─ @types/yargs-parser@20.2.1
├─ @types/yargs@17.0.8
├─ ajv-keywords@3.5.2
├─ ajv@6.12.6
├─ ansi-align@3.0.1
├─ ansi-regex@5.0.1
├─ ansi-styles@4.3.0
├─ app-builder-bin@3.7.1
├─ argparse@2.0.1
├─ asar@3.1.0
├─ assert-plus@1.0.0
├─ astral-regex@2.0.0
├─ async@0.9.2
├─ asynckit@0.4.0
├─ at-least-node@1.0.0
├─ balanced-match@1.0.2
├─ base64-js@1.5.1
├─ bluebird@3.7.2
├─ boxen@5.1.2
├─ brace-expansion@1.1.11
├─ buffer-alloc-unsafe@1.1.0
├─ buffer-alloc@1.2.0
├─ buffer-equal@1.0.0
├─ buffer-fill@1.0.0
├─ buffer-from@1.1.2
├─ buffer@5.7.1
├─ cacheable-request@6.1.0
├─ camelcase@6.2.1
├─ ci-info@3.3.0
├─ cli-boxes@2.2.1
├─ cli-truncate@2.1.0
├─ cliui@7.0.4
├─ clone-response@1.0.2
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ colors@1.0.3
├─ combined-stream@1.0.8
├─ commander@2.9.0
├─ compare-version@0.1.2
├─ concat-map@0.0.1
├─ configstore@5.0.1
├─ core-util-is@1.0.2
├─ crc@3.8.0
├─ cross-spawn@7.0.3
├─ crypto-random-string@2.0.0
├─ debug@4.3.3
├─ decompress-response@3.3.0
├─ deep-extend@0.6.0
├─ defer-to-connect@1.1.3
├─ delayed-stream@1.0.0
├─ dir-compare@2.4.0
├─ dmg-builder@22.14.5
├─ dmg-license@1.0.10
├─ dot-prop@5.3.0
├─ dotenv-expand@5.1.0
├─ dotenv@9.0.2
├─ duplexer3@0.1.4
├─ ejs@3.1.6
├─ electron-builder@22.14.5
├─ electron-osx-sign@0.5.0
├─ electron-publish@22.14.5
├─ emoji-regex@8.0.0
├─ end-of-stream@1.4.4
├─ escalade@3.1.1
├─ escape-goat@2.1.1
├─ escape-string-regexp@1.0.5
├─ extsprintf@1.4.1
├─ fast-deep-equal@3.1.3
├─ fast-json-stable-stringify@2.1.0
├─ filelist@1.0.2
├─ form-data@4.0.0
├─ fs.realpath@1.0.0
├─ get-caller-file@2.0.5
├─ get-stream@4.1.0
├─ glob@7.2.0
├─ global-dirs@3.0.0
├─ got@9.6.0
├─ graceful-fs@4.2.8
├─ graceful-readlink@1.0.1
├─ has-flag@4.0.0
├─ has-yarn@2.1.0
├─ hosted-git-info@4.0.2
├─ http-cache-semantics@4.1.0
├─ iconv-corefoundation@1.1.7
├─ iconv-lite@0.6.3
├─ ieee754@1.2.1
├─ import-lazy@2.1.0
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ ini@2.0.0
├─ is-fullwidth-code-point@3.0.0
├─ is-installed-globally@0.4.0
├─ is-npm@5.0.0
├─ is-obj@2.0.0
├─ is-path-inside@3.0.3
├─ is-yarn-global@0.3.0
├─ isbinaryfile@4.0.8
├─ isexe@2.0.0
├─ jake@10.8.2
├─ json-buffer@3.0.0
├─ json-schema-traverse@0.4.1
├─ json5@2.2.0
├─ keyv@3.1.0
├─ latest-version@5.1.0
├─ lodash@4.17.21
├─ lowercase-keys@1.0.1
├─ make-dir@3.1.0
├─ mime-db@1.51.0
├─ mime-types@2.1.34
├─ mime@2.6.0
├─ ms@2.1.2
├─ node-addon-api@1.7.2
├─ normalize-url@4.5.1
├─ once@1.4.0
├─ p-cancelable@1.1.0
├─ package-json@6.5.0
├─ path-is-absolute@1.0.1
├─ path-key@3.1.1
├─ plist@3.0.4
├─ prepend-http@2.0.0
├─ punycode@2.1.1
├─ pupa@2.1.1
├─ registry-auth-token@4.2.1
├─ registry-url@5.1.0
├─ require-directory@2.1.1
├─ responselike@1.0.2
├─ rimraf@3.0.2
├─ safer-buffer@2.1.2
├─ sanitize-filename@1.6.3
├─ sax@1.2.4
├─ semver-diff@3.1.1
├─ semver@6.3.0
├─ shebang-command@2.0.0
├─ shebang-regex@3.0.0
├─ signal-exit@3.0.6
├─ slice-ansi@3.0.0
├─ smart-buffer@4.2.0
├─ source-map-support@0.5.21
├─ source-map@0.6.1
├─ stat-mode@1.0.0
├─ strip-json-comments@2.0.1
├─ supports-color@7.2.0
├─ tmp-promise@3.0.3
├─ tmp@0.2.1
├─ to-readable-stream@1.0.0
├─ truncate-utf8-bytes@1.0.2
├─ type-fest@0.20.2
├─ typedarray-to-buffer@3.1.5
├─ unique-string@2.0.0
├─ update-notifier@5.1.0
├─ uri-js@4.4.1
├─ url-parse-lax@3.0.0
├─ utf8-byte-length@1.0.4
├─ verror@1.10.1
├─ which@2.0.2
├─ widest-line@3.1.0
├─ write-file-atomic@3.0.3
├─ xmlbuilder@15.1.1
├─ y18n@5.0.8
├─ yallist@4.0.0
├─ yargs-parser@21.0.0
└─ yargs@17.3.1
✨  Done in 17.33s.
%  ls -al node_modules/dmg-license              
total 88
drwxr-xr-x    9 rpatrick  staff    288 Dec 31 17:25 .
drwxr-xr-x  199 rpatrick  staff   6368 Dec 31 17:26 ..
-rw-r--r--    1 rpatrick  staff   1070 Dec 31 17:25 LICENSE
-rw-r--r--    1 rpatrick  staff   1995 Dec 31 17:25 README.md
drwxr-xr-x    3 rpatrick  staff     96 Dec 31 17:26 bin
-rw-r--r--    1 rpatrick  staff  21188 Dec 31 17:25 language-info.json
drwxr-xr-x   23 rpatrick  staff    736 Dec 31 17:26 lib
-rw-r--r--    1 rpatrick  staff   1887 Dec 31 17:25 package.json
-rw-r--r--    1 rpatrick  staff   6512 Dec 31 17:25 schema.json
% 
```

**Comment by pranavwani** [comment]
Hi, @robertpatrick exactly. May be I'm wrong please checkout the source code may be something wrong where in current release imported 'dmg-license' into the same package in 'dmgLicense.ts' which was removed in v29

[v22](https://github.com/electron-userland/electron-builder/blob/87300278d24e8304caa4b053b883843a2447dab2/packages/dmg-builder/src/dmgLicense.ts#L7)

[v29](https://github.com/electron-userland/electron-builder/blob/775c2553775c10b3c9b8ee6e86022b7f02aa8aa8/packages/dmg-builder/src/dmgLicense.ts#L7)

**Comment by rpatrick00** [comment]
@pranavwani But it is still there in master…

https://github.com/electron-userland/electron-builder/blob/87300278d24e8304caa4b053b883843a2447dab2/packages/dmg-builder/src/dmgLicense.ts#L7

**Comment by pranavwani** [comment]
Actually I thought this is the problem that module imported in its own source code 'dmg-license' into in its source code which will be fixed in upcoming release v29

I've test with

Electron-Builder Version: 22.14.5
Node Version: v14.17.3
Electron Version: v12.0.0
Electron Type (current, beta, nightly): current
Electron Update Version: v4.6.1

Still need to figure out

**Comment by pranavwani** [comment]
@rpatrick00 any other possible solution?

**Comment by robertpatrick** [comment]
@pranavwani While I'm not using yarn, my current project (https://github.com/oracle/weblogic-toolkit-ui) is using electron-builder and we are not seeing this problem.  There is a smaller example at https://github.com/robertpatrick/electron-updater-example (a fork from another project) that you could try out to see if it works for you.

**Comment by pranavwani** [comment]
Thanks for sharing @rpatrick00. I'll check it out

And happy new year 🎉

**Comment by pranavwani** [comment]
Temporary fix by set dependency

Electron updater: v4.3.9
Electron builder: v22.10.5

**Comment by robertpatrick** [comment]
@pranavwani The other option is to move to the `next` version of electron-builder.  I am currently using the `next` version of both electron-builder and electron-updates to pick up fixes that I need.

**Comment by pranavwani** [comment]
Yeah this should work. Just need to check thanks

**Comment by pranavwani** [comment]
@lyswhut try to check following solutions
- https://github.com/electron-userland/electron-builder/issues/6520#issuecomment-1003515465
- https://github.com/electron-userland/electron-builder/issues/6520#issuecomment-1003490223

**Comment by robertpatrick** [comment]
@mmaietta I think this is resolved so you can close it

**Comment by catdad** [comment]
For anyone who lands here like me. This issue is not really resolved, and it is not really so much an issue with this module. But it is an issue nonetheless.

This happens to me all the time due to the way I update dependencies. Usually, I delete my package-lock.json and node modules, and then I reinstall. This recreates the package-lock.json file with all the latest modules, respecting semver. If tests pass, there's a good chance everything is still fine. Problem solves, right?

Well, this is where the issue described here occurs. I develop on Windows (sometimes even Linux), but never a Mac. This project, however, has optional dependencies that install only on a Mac. Well... guess what happens when I create my package-lock.json file on Windows? Those optional dependencies are missing. Or... at least the dependencies of those optional dependencies are missing. Later, when the project is installed on a Mac (like in CI), it fails to install those missing dependencies, and building fails.

Since I forget every time and have to search for it, here is how I fix it (without a Mac... if you have a Mac, just generate a package-lock.json file there):

* Find the parent of the missing module.
* Install that parent with `--force`... in the case of `cli-truncate`, I run `npm i -D dmg-license -f`
* This will add `dmg-license` to your package.json file, where you don't want it... delete it
* Run `npm i` again

When looking at your package-lock.json file, now you should see that `cli-truncate` has been added to it. Commit that change.

As for who actually needs to fix what: I have no clue 🤷‍♀️. This is probably an npm bug?

**Comment by robertpatrick** [comment]
Seems like a bad interaction between package-lock.json and optional packages to me…

**Comment by theryansmee** [comment]
> For anyone who lands here like me. This issue is not really resolved, and it is not really so much an issue with this module. But it is an issue nonetheless.
> 
> This happens to me all the time due to the way I update dependencies. Usually, I delete my package-lock.json and node modules, and then I reinstall. This recreates the package-lock.json file with all the latest modules, respecting semver. If tests pass, there's a good chance everything is still fine. Problem solves, right?
> 
> Well, this is where the issue described here occurs. I develop on Windows (sometimes even Linux), but never a Mac. This project, however, has optional dependencies that install only on a Mac. Well... guess what happens when I create my package-lock.json file on Windows? Those optional dependencies are missing. Or... at least the dependencies of those optional dependencies are missing. Later, when the project is installed on a Mac (like in CI), it fails to install those missing dependencies, and building fails.
> 
> Since I forget every time and have to search for it, here is how I fix it (without a Mac... if you have a Mac, just generate a package-lock.json file there):
> 
> * Find the parent of the missing module.
> * Install that parent with `--force`... in the case of `cli-truncate`, I run `npm i -D dmg-license -f`
> * This will add `dmg-license` to your package.json file, where you don't want it... delete it
> * Run `npm i` again
> 
> When looking at your package-lock.json file, now you should see that `cli-truncate` has been added to it. Commit that change.
> 
> As for who actually needs to fix what: I have no clue 🤷‍♀️. This is probably an npm bug?

This comment is absolutely spot on. Thank you for shedding some light and giving a solution 🔥

**Comment by gRoussac** [comment]
Hi, It is reproduced on Linux with `electron-builder --mac`

```
    "electron": "^26.1.0",
    "electron-builder": "^24.6.3",
    "electron-updater": "^6.1.1"
```
with 
```
node v20.5.1
npm 9.8.1
```
adding
```
    "dmg-license": "^1.0.11",
```
leads to another error

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for dmg-license@1.0.11: wanted {"os":"darwin"} (current: {"os":"linux"})
npm ERR! notsup Valid os:  darwin
npm ERR! notsup Actual os: linux
```
Changing to linux in package.json leads to 
    
`electron/node_modules/iconv-corefoundation/lib/native.node: invalid ELF header`
    
`electron-builder --win --linux`  seems to execute to the end however

not sure if it is me trying to emit an dmg on Linux or a bug in last versions.

**Comment by undergroundwires** [comment]
I had the same issue with `24.6.4`, I tried different solutions and the cleanest solution I found which works cross operating systems consistently and represents the intention explicitly in code was:

```sh
npm install "dmg-license" --save-optional
```

This adds following lines to package.json:

```sh
  "optionalDependencies": {
    "dmg-license": "^1.0.11"
  },
```
