### ISSUE TITLE
Wrong version of dependencies pulled into build

### ISSUE THREAD

**Issue by Julusian** [electron-userland/electron-builder#7745]
* **Electron-Builder Version**: 24.6.4 / 24.6.3 / 23.6.0

* **Node Version**: 18.16.0 / 18.15.0

* **Electron Version**: 26.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: linux-x64 (also confirmed in the original project on windows-x64 and mac-arm64)

I have a project where the builds starting failing on a commit that looked like it should have no impact on the electron application. 
It started failing with an error such as:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/julus/electron-builder-bug/electron/dist/linux-unpacked/resources/app.asar/node_modules/debounce-fn/node_modules/mimic-fn/index.js from /home/julus/electron-builder-bug/electron/dist/linux-unpacked/resources/app.asar/node_modules/debounce-fn/index.js not supported.
```
Upon further inspection of the built application, the dependency at `app.asar/node_modules/debounce-fn/node_modules/mimic-fn` was wrong in multiple ways:
* the version of  `app.asar/node_modules/debounce-fn/node_modules/mimic-fn` was not compatible with the semver range specified in `app.asar/node_modules/debounce-fn`
* the version of `app.asar/node_modules/debounce-fn/node_modules/mimic-fn` was not present anywhere in the dependency tree of the electron portion of the app.
* there was no `node_modules/debounce-fn/node_modules/mimic-fn` in the electron portion of the project

I have made a minimal reproduction of the issue: https://github.com/Julusian/electron-builder-wrong-nested-dependency

The steps to reproduce the issue are:
1) Run `yarn` (or `npm i`) at the root level of the repository
2) Run `yarn` (or `npm i`) inside the electron directory
3) Run `npx electron-builder --dir` inside the electron directory
4) Attempt to run the built application, it will fail with the error above

You can confirm it is pulling in the wrong dependency by:
1) cd into `dist/linux-unpacked/resources` and run `npx asar e app.asar app`. this will extract the asar file, so its contents can be viewed
2) inside the newly extraced app folder, you can see that the file `app/node_modules/debounce-fn/node_modules/mimic-fn/package.json` shows it as version `4.0.0`
3) Checking `app/node_modules/debounce-fn/package.json` this is not a compatible version
4) Checking in the `electron` folder where the build command was run, `node_modules/debounce-fn/node_modules` does not exist
5) looking inside the yarn.lock/package-lock.json files of the repository you can see that this dependency is only used as a transitive dependency in the parent directory, for a different version of the same `debounce-fn` library.
6) Delete the root level `node_modules`
7) Rebuild the electron application
8) Run the built application, and it will no longer error

**Comment by Julusian** [comment]
This looks to be improved by https://github.com/develar/app-builder/pull/89, but maybe not entirely fixed. It is no longer pulling in the incompatible dependency, but is pulling in a dependency unnecessarily from the parent directory.

Running with `DEBUG=*`, the ` command=app-builder` step produced the following.
Without that PR: 
```
[
   {
      "dir":"/home/julus/electron-builder-bug/node_modules",
      "deps":[
         {
            "name":"debounce-fn",
            "version":"5.1.2"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/electron/node_modules",
      "deps":[
         {
            "name":"ajv-formats",
            "version":"2.1.1"
         },
         {
            "name":"atomically",
            "version":"1.7.0"
         },
         {
            "name":"conf",
            "version":"10.2.0"
         },
         {
            "name":"debounce-fn",
            "version":"4.0.0"
         },
         {
            "name":"dot-prop",
            "version":"6.0.1"
         },
         {
            "name":"electron-store",
            "version":"8.1.0"
         },
         {
            "name":"env-paths",
            "version":"2.2.1"
         },
         {
            "name":"fast-deep-equal",
            "version":"3.1.3"
         },
         {
            "name":"find-up",
            "version":"3.0.0"
         },
         {
            "name":"is-obj",
            "version":"2.0.0"
         },
         {
            "name":"json-schema-typed",
            "version":"7.0.3"
         },
         {
            "name":"locate-path",
            "version":"3.0.0"
         },
         {
            "name":"lru-cache",
            "version":"6.0.0"
         },
         {
            "name":"mimic-fn",
            "version":"3.1.0"
         },
         {
            "name":"onetime",
            "version":"5.1.2"
         },
         {
            "name":"p-limit",
            "version":"2.3.0"
         },
         {
            "name":"p-locate",
            "version":"3.0.0"
         },
         {
            "name":"p-try",
            "version":"2.2.0"
         },
         {
            "name":"path-exists",
            "version":"3.0.0"
         },
         {
            "name":"pkg-up",
            "version":"3.1.0"
         },
         {
            "name":"punycode",
            "version":"2.3.0"
         },
         {
            "name":"require-from-string",
            "version":"2.0.2"
         },
         {
            "name":"type-fest",
            "version":"2.19.0"
         },
         {
            "name":"uri-js",
            "version":"4.4.1"
         },
         {
            "name":"yallist",
            "version":"4.0.0"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/node_modules/debounce-fn/node_modules",
      "deps":[
         {
            "name":"mimic-fn",
            "version":"4.0.0"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/electron/node_modules/ajv-formats/node_modules",
      "deps":[
         {
            "name":"ajv",
            "version":"8.12.0"
         },
         {
            "name":"json-schema-traverse",
            "version":"1.0.0"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/electron/node_modules/conf/node_modules",
      "deps":[
         {
            "name":"ajv",
            "version":"8.12.0"
         },
         {
            "name":"json-schema-traverse",
            "version":"1.0.0"
         },
         {
            "name":"semver",
            "version":"7.5.4"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/electron/node_modules/onetime/node_modules",
      "deps":[
         {
            "name":"mimic-fn",
            "version":"2.1.0"
         }
      ]
   }
]
```

With that PR:
```
[
   {
      "dir":"/home/julus/electron-builder-bug/node_modules",
      "deps":[
         {
            "name":"mimic-fn",
            "version":"2.1.0"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/electron/node_modules",
      "deps":[
         {
            "name":"conf",
            "version":"10.2.0"
         },
         {
            "name":"debounce-fn",
            "version":"4.0.0"
         },
         {
            "name":"electron-store",
            "version":"8.1.0"
         },
         {
            "name":"find-up",
            "version":"3.0.0"
         },
         {
            "name":"is-obj",
            "version":"2.0.0"
         },
         {
            "name":"locate-path",
            "version":"3.0.0"
         },
         {
            "name":"mimic-fn",
            "version":"3.1.0"
         },
         {
            "name":"p-limit",
            "version":"2.3.0"
         },
         {
            "name":"p-locate",
            "version":"3.0.0"
         },
         {
            "name":"p-try",
            "version":"2.2.0"
         },
         {
            "name":"path-exists",
            "version":"3.0.0"
         },
         {
            "name":"punycode",
            "version":"2.3.0"
         },
         {
            "name":"type-fest",
            "version":"2.19.0"
         },
         {
            "name":"yallist",
            "version":"4.0.0"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/electron/node_modules/ajv-formats/node_modules",
      "deps":[
         {
            "name":"ajv",
            "version":"8.12.0"
         },
         {
            "name":"fast-deep-equal",
            "version":"3.1.3"
         },
         {
            "name":"json-schema-traverse",
            "version":"1.0.0"
         },
         {
            "name":"require-from-string",
            "version":"2.0.2"
         },
         {
            "name":"uri-js",
            "version":"4.4.1"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/electron/node_modules/conf/node_modules",
      "deps":[
         {
            "name":"ajv",
            "version":"8.12.0"
         },
         {
            "name":"ajv-formats",
            "version":"2.1.1"
         },
         {
            "name":"atomically",
            "version":"1.7.0"
         },
         {
            "name":"debounce-fn",
            "version":"4.0.0"
         },
         {
            "name":"dot-prop",
            "version":"6.0.1"
         },
         {
            "name":"env-paths",
            "version":"2.2.1"
         },
         {
            "name":"fast-deep-equal",
            "version":"3.1.3"
         },
         {
            "name":"json-schema-traverse",
            "version":"1.0.0"
         },
         {
            "name":"json-schema-typed",
            "version":"7.0.3"
         },
         {
            "name":"lru-cache",
            "version":"6.0.0"
         },
         {
            "name":"onetime",
            "version":"5.1.2"
         },
         {
            "name":"pkg-up",
            "version":"3.1.0"
         },
         {
            "name":"require-from-string",
            "version":"2.0.2"
         },
         {
            "name":"semver",
            "version":"7.5.4"
         },
         {
            "name":"uri-js",
            "version":"4.4.1"
         }
      ]
   },
   {
      "dir":"/home/julus/electron-builder-bug/electron/node_modules/onetime/node_modules",
      "deps":[
         {
            "name":"mimic-fn",
            "version":"2.1.0"
         }
      ]
   }
]
```

**Comment by Julusian** [comment]
However, trying that in the real project results in it attempting to copy files which dont exist

**Comment by Julusian** [comment]
I have found the bug in `app-builder-bin`, and have a fix https://github.com/develar/app-builder/pull/91. I don't expect to see that PR merged, but hopefully this issue and the PR can be used as motivation to rewrite this in node so that it can be better maintained

As I am using yarn in my project, I can inject my patched version of the lib with:
```
	"resolutions": {
		"app-builder-bin": "npm:@julusian/app-builder-bin#v4.0.1"
	},
```

**Comment by Julusian** [comment]
Still an issue

**Comment by mmaietta** [comment]
Might be an issue, but not something I can solve without upstream being fixed. Tempted to close this ticket because of that reason...

Feel free to tag me once upstream fix has been merged and I'll reopen the issue.

**Comment by Julusian** [comment]
For reference, this is still a problem with 24.13.3 and 25.0.0-alpha.6

**Comment by beyondkmp** [comment]
@Julusian deploying release v25.1.6 now. Please update when you have a chance

**Comment by Julusian** [comment]
I haven't re-tested this case, but updating another project to the latest electron and electron-builder and it encountered a similar issue. Dropping back to the same version of electron-builder and app-builder-bin I am using to fix this allows the build to run at least.

In this other case, inside the node_modules before packaging is the layout
* color
* sharp/node_modules/color
* color-string

And inside the asar is:
* color
* sharp/node_modules/color
* color/node_modules/color-string

The problem here is that color requires color-string.
And in the asar, there is no suitable version of this for the sharp version to find, so the application fails to launch.

This was tested with 25.1.8, so it is still doing some unexpected mangling of the node_modules layout.

**Comment by beyondkmp** [comment]
@Julusian 

> * **Electron-Builder Version**: 24.6.4 / 24.6.3 / 23.6.0 / 24.13.3 / 25.0.0-alpha.6
> 
> * **Node Version**: 18.16.0 / 18.15.0
> 
> * **Electron Version**: 26.1.0
> * **Electron Type (current, beta, nightly)**: current
> 
> * **Target**: linux-x64 (also confirmed in the original project on windows-x64 and mac-arm64)
> 
> I have a project where the builds starting failing on a commit that looked like it should have no impact on the electron application. It started failing with an error such as:
> 
> ```
> Error [ERR_REQUIRE_ESM]: require() of ES Module /home/julus/electron-builder-bug/electron/dist/linux-unpacked/resources/app.asar/node_modules/debounce-fn/node_modules/mimic-fn/index.js from /home/julus/electron-builder-bug/electron/dist/linux-unpacked/resources/app.asar/node_modules/debounce-fn/index.js not supported.
> ```
> 
> Upon further inspection of the built application, the dependency at `app.asar/node_modules/debounce-fn/node_modules/mimic-fn` was wrong in multiple ways:
> 
> * the version of  `app.asar/node_modules/debounce-fn/node_modules/mimic-fn` was not compatible with the semver range specified in `app.asar/node_modules/debounce-fn`
> * the version of `app.asar/node_modules/debounce-fn/node_modules/mimic-fn` was not present anywhere in the dependency tree of the electron portion of the app.
> * there was no `node_modules/debounce-fn/node_modules/mimic-fn` in the electron portion of the project
> 
> I have made a minimal reproduction of the issue: https://github.com/Julusian/electron-builder-wrong-nested-dependency
> 
> The steps to reproduce the issue are:
> 
> 1. Run `yarn` (or `npm i`) at the root level of the repository
> 2. Run `yarn` (or `npm i`) inside the electron directory
> 3. Run `npx electron-builder --dir` inside the electron directory
> 4. Attempt to run the built application, it will fail with the error above
> 
> You can confirm it is pulling in the wrong dependency by:
> 
> 1. cd into `dist/linux-unpacked/resources` and run `npx asar e app.asar app`. this will extract the asar file, so its contents can be viewed
> 2. inside the newly extraced app folder, you can see that the file `app/node_modules/debounce-fn/node_modules/mimic-fn/package.json` shows it as version `4.0.0`
> 3. Checking `app/node_modules/debounce-fn/package.json` this is not a compatible version
> 4. Checking in the `electron` folder where the build command was run, `node_modules/debounce-fn/node_modules` does not exist
> 5. looking inside the yarn.lock/package-lock.json files of the repository you can see that this dependency is only used as a transitive dependency in the parent directory, for a different version of the same `debounce-fn` library.
> 6. Delete the root level `node_modules`
> 7. Rebuild the electron application
> 8. Run the built application, and it will no longer error

v26.0.0-alpha.1 has already resolved this issue. In my current local testing, I'm no longer able to reproduce it.

**Comment by beyondkmp** [comment]
> 25.1.8

I cannot

> I haven't re-tested this case, but updating another project to the latest electron and electron-builder and it encountered a similar issue. Dropping back to the same version of electron-builder and app-builder-bin I am using to fix this allows the build to run at least.
> 
> In this other case, inside the node_modules before packaging is the layout
> 
> * color
> * sharp/node_modules/color
> * color-string
> 
> And inside the asar is:
> 
> * color
> * sharp/node_modules/color
> * color/node_modules/color-string
> 
> The problem here is that color requires color-string. And in the asar, there is no suitable version of this for the sharp version to find, so the application fails to launch.
> 
> This was tested with 25.1.8, so it is still doing some unexpected mangling of the node_modules layout.

I cannot reproduce it with 25.1.8 and v26.0.0-alpha.1. Here's my config
```
{
  "name": "TestApp",
  "productName": "Test App ßW",
  "description": "My Electron application description",
  "keywords": [],
  "main": "./main.js",
  "version": "1.0.0",
  "author": "beyondkmp",
  "scripts": {
    "start": "electron .",
    "dist": "electron-builder"
  },
  "license": "MIT",
  "build": {
    "appId": "electron-blog-example",
    "win": {
      "target": "nsis"
    }
  },
  "devDependencies": {
    "electron": "32.1.0",
    "electron-builder": "25.1.8"
  },
  "dependencies": {
          "color": "3.2.1",
          "sharp":"0.33.5",
          "color-string":"1.9.1"

  }
}
```
